### ISSUE TITLE
"Too Many Skills Selected" issue

### ISSUE THREAD

**Issue by kypvalanx** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#100]
The "Too Many Skills Selected" issue seems to return every time after F5 refresh, but will disappear when "making any change to the sheet" in any manner. Seem like making change force the sheet to update and get rid of the erroneous warning. But the warning will be coming back after refresh.  

breaking this out from #97

**Comment by sanpats** [comment]
It's first appear in version 0.4.15, doesn't happen before.
