### ISSUE TITLE
Assign Abilities Score Points Window bug out

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#102]
Possibly related to #100.

After refresh (F5), Assign Abilities Score Points Window bug out. (Please note a yellow "!" under the ability scores)
![image](https://user-images.githubusercontent.com/22677493/151118983-6d9ac5d8-0dbc-4ba3-8cd9-f11d800f2e36.png)

Make any change to the sheet will fix it, until another refresh.
![image](https://user-images.githubusercontent.com/22677493/151119037-83515f7f-7753-489f-af8c-abd70db0aa5b.png)

**Comment by kypvalanx** [comment]
i think you're right, i think it is the same problem as #100 .  it looks like a race condition.
