### ISSUE TITLE
Species options for droids missing.

### ISSUE THREAD

**Issue by BangoeRette** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#103]
This seems to be new with one of the recent updates. Currently running 0.4.16. All degrees of droids are no longer selectable in the Species folder.

Screenshot 1: Top of the alphabetical list (used to have nth degree droid)
![image](https://user-images.githubusercontent.com/93169227/151237718-54286155-b386-4bd7-b2d9-f064327e46db.png)

Screenshot 2: Searching "droid" only brings up Replica Droid.
![image](https://user-images.githubusercontent.com/93169227/151237810-70b575a3-75b3-4a9e-a6a6-9eea529e6e0e.png)

**Comment by sanpats** [comment]
Must be 0.4.16, because I made a droid npc in 0.4.15.

**Comment by sanpats** [comment]
Probably 0.4.15 because there was an compendium update in that version.

**Comment by kypvalanx** [comment]
I'll give it a look before work.  I had to change how I was scraping the data last time I did it
