### ISSUE TITLE
version 2.3 - feat added bug

### ISSUE THREAD

**Issue by jasony1974** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#11]
version 2.3 does not solve the "Feat added" bug.

Here are the steps I followed:

1. create new actor - character
2. set ability scores
3. add species
4. add general feat

First screen shot is after step 3, adding the species, the traits for the species are displayed, but the name of the species is not. 

After adding the general feat - I used "Improved Defenses" - the Defense, Offense, Attacks, and Abilities sections of the Summary tab are blanked out, the Feat doesn't display on the Feats tab, but the General Feats warning is gone. 

If I close & reopen the character sheet, the Feat is displayed, but the sections on the summary tab return to being blank, and the General Feat warning appears again. If I remove the feat, by clicking the trash can icon, the sections on the summary tab repopulate.
![test character 2 3 - ability scores added, species chosen](https://user-images.githubusercontent.com/79643334/116586448-7a6fef80-a8e7-11eb-8c66-ac5eaba7320b.png)
![test character 2 3 - general feat added, summary tab data missing](https://user-images.githubusercontent.com/79643334/116586452-7cd24980-a8e7-11eb-81f2-086133f81baf.png)

**Comment by kypvalanx** [comment]
can you add any error logs as well?  hit F12 to open the console.

**Comment by jasony1974** [comment]
See attached.
![test character 2 3 - general feat added, console log](https://user-images.githubusercontent.com/79643334/116590740-1c91d680-a8ec-11eb-8cbf-73ad0736ef20.png)

**Comment by kypvalanx** [comment]
give 0.2.4 a try, i'm not sure how yours is failing.  i installed from the zip on a seperate instance and that feat's data appeared fine and i was able to add it.

**Comment by jasony1974** [comment]
0.2.4 seems to have solved the Feat added issue!  There are new issues to tackle now, but that's a big step forward.
