### ISSUE TITLE
[V9] Skill Focus for knowledge skills doesn't work

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#115]
![image](https://user-images.githubusercontent.com/22677493/152151066-d9af66c2-65d7-4fb8-ba28-ae1038b12b54.png)
![image](https://user-images.githubusercontent.com/22677493/152151111-f3976c45-3e84-4e7c-b84f-876bc283ab29.png)

I think the standalone Skill Focus feat have a wrong requirement for knowledge skills. If Skill Focus feat is added from nonheroic free feat, it works, with requirement "Trained in Knowledge (XXX)". But the standalone Skill Focus feat (the one manually selected from the compendium has "Trained in K. (XXX)" instead.

**Comment by sanpats** [comment]
This one is from nonheroic class, which works.
![image](https://user-images.githubusercontent.com/22677493/152151732-3345476e-f8d7-4538-b1aa-60e638033979.png)

**Comment by kypvalanx** [comment]
can you add a label for the version you are using?  0.4.X will only receive bug fixes (this would qualify) V9 will get enhancements

**Comment by kypvalanx** [comment]
also, i think you're right in your evaluation of the problem

**Comment by sanpats** [comment]
I can't add a label, may be because I am not a participant/contributor?
![image](https://user-images.githubusercontent.com/22677493/152277378-01bea3ab-a681-4864-8ee4-c1dbc401ccb9.png)
No gear icon after the label.

It's V9.

**Comment by sanpats** [comment]
I use 0.5.0
