### ISSUE TITLE
[enhancement] Vehicle Character Sheet

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#120]
Request an ability to create vehicle character sheet in the future.

**Comment by kypvalanx** [comment]
started

**Comment by kypvalanx** [comment]
running into a rule inconsistency.  weapons have stats listing a certain damage.  existing vehicles have those weapons installed but have a different damage listed. i'm considering creating a variant of that weapon with the vehicles name on it that has the vehicle listed damage

**Comment by sanpats** [comment]
Far example? Are you sure it isn't typos that was corrected by the errata?

**Comment by kypvalanx** [comment]
the Z-95 headhunter has medium concussion missiles but they are stated like light concussion missiles.  https://swse.fandom.com/wiki/Z-95_Headhunter  i also checked the book.

**Comment by sanpats** [comment]
Personally, I think it's just a typo.

**Comment by kypvalanx** [comment]
It's very consistent how inconsistent these blocks are.  i can compare all of the instances where weapons are used while generating the stat blocks and even after accounting for modifiers these blocks don't match the build your own parts that are in the same book.

**Comment by kypvalanx** [comment]
i think for now i'm going to add the items as named and worry about the inconsistencies later.
