### ISSUE TITLE
[enhancement] Custom contents

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#121]
Request an ability for enduser to create custom items such as species, equipments, etc.

**Comment by kypvalanx** [comment]
this requires a few new features:
[/] attributes are visible and mutable
[/] modes are visible and mutable
[x] buffs are visible and mutable
[x] item type and subtype are mutable
[x] provided items are visible and mutable
[x] prerequisites are visible and mutable

there might be other old fields i haven't updated to attributes yet, and those should be moved over.
