### ISSUE TITLE
[enhancement] Generic Sheet

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#122]
Alternative to or in addition to the custom content creation (see #121), give us a generic sheet would be useful. A generic sheet is an empty character sheet that has no automatic calculation in any field. Users can put any value in any field themselves. Species is just a text field etc.

**Comment by kypvalanx** [comment]
i'm trying to think about how this would work.  would it just be a text area where you can include rollable links in the text?  should some fields exist?  i think if you described your use case in greater detail i could come up with more.

**Comment by LeKopic** [comment]
The idea, I think, is to have (almost) every field not be connected to any other, letting users to input data into any field without it affecting anything else (traits, attacks, skills), while the general design and composition of a charsheet stays the same.
Basically, Foundry + existing character sheet layout (but like that):
![image](https://user-images.githubusercontent.com/42682507/173207950-6c47b027-82fe-457d-b886-97873080fae5.png)

**Comment by kypvalanx** [comment]
@sanpats does that sum it up pretty well?

**Comment by sanpats** [comment]
@kypvalanx Yes. spot on.

**Comment by kypvalanx** [comment]
@sanpats i've started making changes to the mainsheet and created a manual sheet, so far the summary section and the ability score sections are functional.

**Comment by sanpats** [comment]
Great!

**Comment by kypvalanx** [comment]
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/0.6.16

this has been released.
