### ISSUE TITLE
Game master creates something

### ISSUE THREAD

**Issue by kypvalanx** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#130]
player sees: 

game:1 Uncaught (in promise) Error: User Player 1 lacks permission to update Actor [IpTEyVKYRmm1MBff]
    at ServerDatabaseBackend._updateDocuments

**Comment by Derinzed** [comment]
I'm beginning a migration to this system, and I'm experiencing this.  Every time I create an actor, one of my players gets this popup.

**Comment by LeKopic** [comment]
Oh, yeah, it is a constant issue for my players as far as I know. I think it happens every time I edit a character sheet, but I didn't investigate it thoroughly. 
Not really a big deal, as the pop-ups are limited to 3 max. at a time (I think), but a bit annoying.

**Comment by Derinzed** [comment]
I got you.  I might spend some time taking a look at it if that's ok, it's just a minor annoyance that I think I'd like to not have haha.

**Comment by Derinzed** [comment]
I think I found the issue.  In SWSEActor, everytime prepareData is called (and the subsequent _prepareITEMData calls) it updates the actor, but that method is triggered client side as well, so all users who don't have authority receive that message.

**Comment by kypvalanx** [comment]
> I think I found the issue.  In SWSEActor, everytime prepareData is called (and the subsequent _prepareITEMData calls) it updates the actor, but that method is triggered client side as well, so all users who don't have authority receive that message.  

If you open a pr with the change I'll review it when I get back

**Comment by Derinzed** [comment]
I certainly will.  I've not created a pr before for git, do I need to fork the repo, or should I push it onto the dev branch and create the request from there?

**Comment by kypvalanx** [comment]
you'll have to create a fork since it's still a personal repo.  in the future you'll have to update your fork before submitting changes.

then you make a change in main in your fork and pr to main in the main repo

**Comment by Derinzed** [comment]
Ok great, thanks. I'll get the PR up tonight.
