### ISSUE TITLE
[Bug][V9] Improved Damage Threshold feat doesn't work

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#132]
[Bug][V9] Improved Damage Threshold feat should give +5 bonus to damage threshold.

**Comment by kypvalanx** [comment]
this will be released with the vehicle system.  it's not related, i just put the fix in the same pipeline

**Comment by kypvalanx** [comment]
@sanpats can you add actual labels to things?

**Comment by sanpats** [comment]
What do you mean? If you mean github label, no I can't.

**Comment by kypvalanx** [comment]
ok, no problem.  this should be fixed with  #0.5.2
