### ISSUE TITLE
[Bug] Can't add talents to Force Prodigy's sheet

### ISSUE THREAD

**Issue by TrinoMG** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#134]
I tried to add different types of talents from Force Talent Trees but it isn't work
![image](https://user-images.githubusercontent.com/29702601/154926620-e5400a41-7d31-4a50-b78b-e6a182c77b15.png)

**Comment by kypvalanx** [comment]
what version are you running and what talent did you add?

**Comment by kypvalanx** [comment]
fixed with [0.5.3](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/tree/0.5.3)
