### ISSUE TITLE
[Bug][V9] Visions talent's requisite can't be fulfilled

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#135]
Visions talent required Farseeing force power, but even if I have one, it's still not recognized as requisite fulfillment.
![image](https://user-images.githubusercontent.com/22677493/155508785-2de14de2-9395-4824-84fb-c6b848c0ecd0.png)

**Comment by kypvalanx** [comment]
will handle after vehicle enhancement

**Comment by kypvalanx** [comment]
fixed by https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/commit/7a0e129118ba7d1d4326ad96ce67301c72496d89

**Comment by kypvalanx** [comment]
fixed with [0.5.3](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/tree/0.5.3)
