### ISSUE TITLE
[Bug][V9] Can't take Force Secrets

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#136]
Even if I have the quota, can't take any Force Secrets.
![image](https://user-images.githubusercontent.com/22677493/155509382-14725430-e54a-44dc-9786-84ab420fe305.png)

**Comment by kypvalanx** [comment]
will fix as part of the vehicle enhancement

**Comment by kypvalanx** [comment]
fixed with [0.5.3](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/tree/0.5.3)
