### ISSUE TITLE
[Bug] [v0.5.1] Conditional Bonus Feat not added

### ISSUE THREAD

**Issue by TalonKetupa** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#137]
The conditional bonus feat (Dual Weapon Mastery I) for the Codru-Ji race is not added to character feats when prerequisites are met. This could also be an issue with all conditional bonus feats. Tested with Herglic race as well and the conditional bonus feat was not added.

**Comment by kypvalanx** [comment]
thank you for the submission.  i'll address this during or after my current enhancement to add vehicles to the system.

**Comment by kypvalanx** [comment]
fixed with [0.5.3](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/tree/0.5.3)
