### ISSUE TITLE
0.2.4 character creation process issues

### ISSUE THREAD

**Issue by jasony1974** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#14]
1). create new character

2). leave attributes at default (10 for all)
	Notes: 
	Character Sheet Warnings displayed: 2
		a). PLEASE SELECT A SPECIES!!
		b). General Feats remaining: 1

3). add species (Mon Calamari)
	Notes: 
	[comment: Species name does not display, and (Use the Force skill - Can use untrained=Y), but otherwise Summary tab looks correct]
	Character Sheet Warnings displayed: 1
		a). General Feats remaining: 1
	Closed Species compendium
	
4). add General Feat (Improved Defenses)
	Notes:
	Character Sheet Warnings displayed: none
	Character Sheet Tab status
		"Improved Defenses" appears of Feats Tab
	Closed Feats compendium

5). add Class (Jedi)
	Notes:
	Dialog box: On First Level...
		Click "OK"
		actor-sheet.js:744 pauses on debugger
		Click "Resume script execution" in console
	Dialog box: Adding Class Starting Feats
		Click "OK"
		Notes:
		Character Sheet Warnings displayed: 2
			a). Jedi Talents remaining: 1
			b). General Feats remaining: -3
		Character Sheet Tab status
			Summary Tab
				"Trained" checkboxes appear in Skills area
			Class Tab
				"Jedi" appears with 1 HP
				[comment: The +1 HP plus the Con modifier of -1 correctly add to 0 HP on the Summary tab]
[comment: Jedi Class should start with 30 HP, plus con modifier]
			Equipment Tab
				"Lightsaber" appears in Unequipped area
			Feats Tab 
				"Force Sensitivity"
				"Weapon Proficiency"
				"Weapon Proficiency"
				[comment: General Feats warning count was at 0, and the addition of these 3 new Feats result in the -3]
	Closed Class compendium

6). Attempt to Equip Lightsaber
	Notes: Clicked & dragged item from unequipped to equipped area.
	[comment: Item moves to appropriate area, but Summary tab still indicates unarmed attack.]
		Attempted to add lightsaber from equipment compendium to summary tab directly
			Created owned item; equipment tab reflected second lightsaber (unequipped)
		Deleted duplicate (unequipped) lightsaber from equipment tab
		Attempted to drag unarmed attack to equipment compendium, which produced error in console.log
			Console.Log Error:
				foundry.js:30367 Uncaught (in promise) TypeError: Cannot read property 'getFlag' of null
   		 		at Function.fromDropData (foundry.js:30367)
    				at Compendium._onDrop (foundry.js:28744)
    				at DragDrop.callback (foundry.js:13525)
    				at DragDrop._handleDrop (foundry.js:13576)
		Closed equipment compendium		

7.) Attempted to add Trained Skills
	Notes: Attempted to click "Trained" in "Use the Force"
	Character Sheet Warnings displayed: 3	
		a). Too Many Skills Selected: 1
		b). Jedi Talents remaining: 1
		c). General Feats remaining: -3
	[comment: Attempting to add more Trained Skills just increased count of warning; unchecked all but Use the Force; too many skill warning: 1]

8). Attempted to add Talents (Jedi Guardian: Battle Meditation)
	Notes: 
	Console.Log Error:
		actor.mjs:130 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    		at SWSEActor.getTalents (actor.mjs:130)
    		at SWSEActor._prepareCharacterData (actor.mjs:41)
   		at async SWSEActor.prepareData (actor.mjs:25)
	Character Sheet fails to render properly:
		Summary Tab
			All Character Sheet Warnings disappear
			All "Trained" checkboxes disappear
			HP increases to 10
			Condition, Defense, Offense, Attacks, and Abilites sections go blank
		Class Tab
			goes blank
		Equipment Tab
			goes blank
		Feats Tab 
			goes blank
		Talents Tab
			Talent fails to appear.
	Closed Talents compendium
	Closed Character Sheet	
		Console.Log Error:
			actor.mjs:130 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    			at SWSEActor.getTalents (actor.mjs:130)
    			at SWSEActor._prepareCharacterData (actor.mjs:41)
   			at async SWSEActor.prepareData (actor.mjs:25)

9). Screen shot of console.log

10). Reopened Character Sheet
	Notes: Character Sheet nearly the same as prior to close, except that 
		new warnings have appeared
		Class tab shows Jedi class, but with no HP
	Character Sheet Warnings displayed: 2
		a). Jedi Talents remaining: 1
		b). General Feats remaining: 1
		[comment: because no Feats are listed, the character sheet is essentially back to its starting condition]

![test character 2 4 - character creation process - console log](https://user-images.githubusercontent.com/79643334/116632041-30592f00-a924-11eb-8ccf-38db83e5c91a.png)

![test character 2 4 - character creation process - summary tab](https://user-images.githubusercontent.com/79643334/116632056-394a0080-a924-11eb-87a0-8346abc1ab3a.png)

![test character 2 4 - character creation process - attributes tab](https://user-images.githubusercontent.com/79643334/116632067-42d36880-a924-11eb-99d9-8eba91fcef2a.png)

![test character 2 4 - character creation process - class tab](https://user-images.githubusercontent.com/79643334/116632075-47981c80-a924-11eb-975a-0dc11e056d09.png)

![test character 2 4 - character creation process - equipment tab](https://user-images.githubusercontent.com/79643334/116632107-5979bf80-a924-11eb-8e31-337c54d64a71.png)

![test character 2 4 - character creation process - feats tab](https://user-images.githubusercontent.com/79643334/116632110-5c74b000-a924-11eb-9ba6-1cd93381f57e.png)

![test character 2 4 - character creation process - talents tab](https://user-images.githubusercontent.com/79643334/116632120-639bbe00-a924-11eb-8ace-b92d4662674b.png)

**Comment by kypvalanx** [comment]
i'll walk through these tonight on the new version and see if the general stability fixes cleaned things up.  i bet plenty of stuff around attacks is still not working as i didn't focus on that.

**Comment by kypvalanx** [comment]
> 1). create new character
> 
> 2). leave attributes at default (10 for all)
> Notes:
> Character Sheet Warnings displayed: 2
> a). PLEASE SELECT A SPECIES!!
> b). General Feats remaining: 1

looks correct so far

>3). add species (Mon Calamari)
>Notes:
>[comment: Species name does not display, and (Use the Force skill - Can use untrained=Y), but otherwise Summary tab looks correct]
>Character Sheet Warnings displayed: 1
>a). General Feats remaining: 1
>Closed Species compendium

this should be corrected in 0.3.0

>4). add General Feat (Improved Defenses)
>Notes:
>Character Sheet Warnings displayed: none
>Character Sheet Tab status
>"Improved Defenses" appears of Feats Tab
>Closed Feats compendium

i don't think this feat has stats implemented

>5). add Class (Jedi)
>Notes:
>Dialog box: On First Level...
>Click "OK"
>actor-sheet.js:744 pauses on debugger
>Click "Resume script execution" in console

i need to make sure i've removed debugger statements before pushing.  i need a CI pipeline.

>Dialog box: Adding Class Starting Feats
>Click "OK"
>Notes:
>Character Sheet Warnings displayed: 2
>a). Jedi Talents remaining: 1
>b). General Feats remaining: -3

looks like they weren't recognizing that they had a source.  should be fixed in 0.3.0

>Character Sheet Tab status
>Summary Tab
>"Trained" checkboxes appear in Skills area
>Class Tab
>"Jedi" appears with 1 HP
>[comment: The +1 HP plus the Con modifier of -1 correctly add to 0 HP on the Summary tab]
>[comment: Jedi Class should start with 30 HP, plus con modifier]

created #17 to address this

>Equipment Tab
>"Lightsaber" appears in Unequipped area
>Feats Tab
>"Force Sensitivity"
>"Weapon Proficiency"
>"Weapon Proficiency"
>[comment: General Feats warning count was at 0, and the addition of these 3 new Feats result in the -3]
>Closed Class compendium

the only issue here was mentioned above and this should be resolved now

>6). Attempt to Equip Lightsaber
>Notes: Clicked & dragged item from unequipped to equipped area.
>[comment: Item moves to appropriate area, but Summary tab still indicates unarmed attack.]

unarmed attack should remain available as an armed person could kick or something, the lightsaber should add however.  i need to look at how i'm handling this because at the moment there is no limit to equipped weapons created #18 to look into this

>Attempted to add lightsaber from equipment compendium to summary tab directly
>Created owned item; equipment tab reflected second lightsaber (unequipped)
>Deleted duplicate (unequipped) lightsaber from equipment tab
>Attempted to drag unarmed attack to equipment compendium, which produced error in console.log
>Console.Log Error:
>foundry.js:30367 Uncaught (in promise) TypeError: Cannot read property 'getFlag' of null
>at Function.fromDropData (foundry.js:30367)
>at Compendium._onDrop (foundry.js:28744)
>at DragDrop.callback (foundry.js:13525)
>at DragDrop._handleDrop (foundry.js:13576)

don't do that :D a future plan is to create a custom compendium viewer that will filter by more categories.  i'll be able to fix this better then.  maybe i can add a catch here #19

>Closed equipment compendium

>7.) Attempted to add Trained Skills
>Notes: Attempted to click "Trained" in "Use the Force"
>Character Sheet Warnings displayed: 3
>a). Too Many Skills Selected: 1
>b). Jedi Talents remaining: 1
>c). General Feats remaining: -3
>[comment: Attempting to add more Trained Skills just increased count of warning; unchecked all but Use the Force; too many skill warning: 1]

this looks absolutely borked and i have no guess #20

>8). Attempted to add Talents (Jedi Guardian: Battle Meditation)
>Notes:
>Console.Log Error:
>actor.mjs:130 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
>at SWSEActor.getTalents (actor.mjs:130)
>at SWSEActor._prepareCharacterData (actor.mjs:41)
>at async SWSEActor.prepareData (actor.mjs:25)
>Character Sheet fails to render properly:
>Summary Tab
>All Character Sheet Warnings disappear
>All "Trained" checkboxes disappear
>HP increases to 10
>Condition, Defense, Offense, Attacks, and Abilites sections go blank
>Class Tab
>goes blank
>Equipment Tab
>goes blank
>Feats Tab
>goes blank
>Talents Tab
>Talent fails to appear.
>Closed Talents compendium
>Closed Character Sheet
>Console.Log Error:
>actor.mjs:130 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
>at SWSEActor.getTalents (actor.mjs:130)
>at SWSEActor._prepareCharacterData (actor.mjs:41)
>at async SWSEActor.prepareData (actor.mjs:25)

used 'toLowerCase' instead of 'toLowerCase()' or it was called on an undefined field #21

9). Screen shot of console.log

>10). Reopened Character Sheet
>Notes: Character Sheet nearly the same as prior to close, except that
>new warnings have appeared
>Class tab shows Jedi class, but with no HP
>Character Sheet Warnings displayed: 2
>a). Jedi Talents remaining: 1
>b). General Feats remaining: 1
>[comment: because no Feats are listed, the character sheet is essentially back to its starting condition]

this is actually the same problem as #21

**Comment by kypvalanx** [comment]
@jasony1974 thank you for your help.  you are significantly better at reporting bugs than professional testers i work with.

**Comment by kypvalanx** [comment]
i've broken this out into smaller issues that refer to this one, i'll close this one
