### ISSUE TITLE
[Enhancement] Make certain items stackable

### ISSUE THREAD

**Issue by TalonKetupa** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#140]
When adding items to the character sheet, duplicate items are added with a new line. This can make item management tedious.
I suggest adding a way to list and modify quantity of each item that exists or a way of letting duplicate items stack with a tracked counter.

For example, if a character has 20 or so rations or power packs, the items currently end up taking an enormous amount of visual space on the character sheet.

**Comment by kypvalanx** [comment]
2 things:
1. i'll add this as an enhancement (it was in future plans but i'll move it up)
2. i really appreciate how well you request changes.  they are specific and polite.  keep it up, i love the feedback.

**Comment by kypvalanx** [comment]
inventory items are now stackable https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/0.5.5
