### ISSUE TITLE
[Enhancement] Implement showing a compendium object's description in the chat log

### ISSUE THREAD

**Issue by TalonKetupa** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#141]
This is to help during gameplay. It allows for quick information sharing between everyone in the group on what an object, trait, item, feat, etc is capable of. This helps keep the GM from having to memorize everything or navigate through all the character pages to find what a player is doing.

**Comment by kypvalanx** [comment]
i think this hsa been requested and i will add reciprocal links tomorrow when i find the request.  this is a good idea that i have seen in the other systems that i play games in
