### ISSUE TITLE
[bug] [v 0.5.1, Foundry v9.255] Cannot add details to created items

### ISSUE THREAD

**Issue by marvinandroid01** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#142]
I didn't see this issue reported previously; if it is a duplicate, I apologize.

When creating a new item in the Items Directory (in my case, story-based equipment, though this also applies for creating new armor and weapons, as well), the only fields that accept any entries are the name, cost, weight, and the Attributes fields (which I find confusing and don't know what those are supposed to accomplish).  There is no way, either when first creating the item or when editing it on a character, to add any text to the Description, Provided, Stripping, or Modifications tabs.  

The problem remains if the Items compendium is duplicated into an unlocked form, the item is copied to the unlocked compendium, and I attempt to edit the item there.

My ultimate request is for the equipment options to allow for new equipment to be created and set so that it can properly apply its modifiers accurately to the character.  That's likely a complicated and time-consuming remedy, so in the interim I ask that you set the "Description" field so that it is editable so that narrative can be added and then applied by the GM/players.

Thank you!  I appreciate the work you have put into developing this for Foundry!

**Comment by marvinandroid01** [comment]
I checked if existing items could be edited while they are on a character.  The icon to edit text in the description appears and I am able to add text there, but those changes do not display even after using the save button or closing and re-opening the sheet.  However, when re-editing the text on existing items, the changes are visible until the text field is no longer being edited.   See images below. 

![image](https://user-images.githubusercontent.com/90999683/156963094-d85b00a2-8f69-4f53-8ff3-19cdc695cd6b.png)
![image](https://user-images.githubusercontent.com/90999683/156963142-2f8a549c-d82d-49a7-9158-1fec1f300b57.png)

The text remains visible while editing when the specific item has been dragged to another character, and the edits do not appear on a freshly-dragged version from the item compendium.

Hopefully this helps identify and resolve the issue!

**Comment by kypvalanx** [comment]
this will be done as part of #121
