### ISSUE TITLE
[v0.5.3] Minor issue with "Full Attack" button

### ISSUE THREAD

**Issue by TalonKetupa** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#145]
I have not experimented much with the "Full Attack" before. I imagine it's purpose is for use with the double and triple attack feats; however, I clicked it on a whim with a created low-level character.

Actions Taken: 
   1.Click "Full Attack"
   2.Dialog opens to select attacks which displays only the "Attack" button. Press this.
Result:
Immediately, an error is returned as follows:
   
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/86027445/158081178-1e977e49-bccf-47d8-acbf-266c40649c87.png">

Console Error message: 
Uncaught Error: TypeError: Cannot read properties of undefined (reading 'name')
    at Dialog.submit (foundry.js:44076)
    at Dialog._onClickButton (foundry.js:44035)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)

Thanks for your awesome hard work!
 I am hoping that I will be able to assist more than just reporting errors. As of yet, I am still getting familiar with javascript.

**Comment by kypvalanx** [comment]
i should have left a note for myself.  when i developed that i didn't know how to resolve unarmed attacks in a full attack, and so i skipped it.  when i figure out how that works i'll update it

**Comment by kypvalanx** [comment]
works as of https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/0.5.4
