### ISSUE TITLE
[Enhancement, Question] Default Token Configuration

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#146]
Good time of day. I tried to set up a Default Token Configuration for every new token with Bar x Attribute"defense.ref.total", but I didn't manage to find such attribute in Default Token config, only in each actors' separate token config. As I am completely new to Foundry I am not sure whether this attribute can be added as a default option because of the several types of actors, but if it is possible - it will help a lot in streamlining setting up tokens. Thanks!

**Comment by kypvalanx** [comment]
I have no idea.  can you post screen shots of your workflow?

**Comment by LeKopic** [comment]
Hm, strange. Just tried it again with a bunch of new tokens/actors - it works perfectly fine. I guess it was some issue on my end, maybe a hiccup with updating token info.

**Comment by LeKopic** [comment]
Never mind. 
![image](https://user-images.githubusercontent.com/42682507/166139275-1eda44b8-8111-43db-a98c-eadd7331c6c4.png)
Game Settings -> Default Token Configuration
![image](https://user-images.githubusercontent.com/42682507/166139306-b653a469-42c1-44f7-b606-7e63f1bbb276.png)
No option to choose defense.ref.total, which exists for each separate actor token. 
![image](https://user-images.githubusercontent.com/42682507/166139339-32ddb6b4-3fda-46ea-adec-cbf5d957bdc7.png)

**Comment by kypvalanx** [comment]
i think i figured this out, and i think i did something wrong with the health bar.  so i'll take a look at both later tonight

**Comment by LeKopic** [comment]
Yeah, the main thing I want from Tokens - to show health and reflex defense. Health is shown ok, but I can only set Reflex Defenses for each Actor separately, which is a bit tedious. 
But it is by no means an important issue.

**Comment by kypvalanx** [comment]
i forgot to include this tag in a release.  this has been working for a few days.

**Comment by kypvalanx** [comment]
fixed: db53b6cc069a0d8e4f2947481cd9789923bf111d
