### ISSUE TITLE
[Bug] Double weapon stun damage

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#147]
Double weapons with Stun setting set do 2d6/2d6 damage, as in division. Nondouble weapons work fine.

**Comment by kypvalanx** [comment]
stun was switched from an additional attribute to a 'mode' recently, can you verify that on a newly added weapon, this is still a problem?

**Comment by LeKopic** [comment]
No longer an issue, but there are some minor issues:
1) It is possible to unselect stun setting for things that only have a stun mode, e.g. Stun Grenade.
2) Some text issues. No space between a "." and "Stun". No "Stun Damage" note for other weapons.
![image](https://user-images.githubusercontent.com/42682507/166504738-236160b8-f848-4f44-aa26-6e3940ede99a.png)
![image](https://user-images.githubusercontent.com/42682507/166504904-aa008ac0-a1da-4e65-bd28-78b4e347c2a6.png)

**Comment by kypvalanx** [comment]
good point.  i only considered stun to be an optional setting.  the attack notes need to be 'joined by a " " to fix 2.  that's an easy fix.  the first is based on a hard design decision that everything is built on.  that will need a bit more work.
