### ISSUE TITLE
[Suggestion] Collapsible armor/weapon entries in Actor Sheet

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#148]
As per request, I transfer my message over from r/SagaEdition individually.

I'd like to see an option to collapse a weapon/armor stats in the Summary actor screen, it tends to get a bit bloated (one of my players, for example, had 8 pistols on them)

**Comment by kypvalanx** [comment]
good idea, i can figure that out.  what are they a female besalisk?

**Comment by LeKopic** [comment]
Near-Human with 4 arms, but they had a bunch of different pistols and other weapons in their inventory.

**Comment by kypvalanx** [comment]
fixed: b53225c36568ca45f55f5c2f139d2e0bf4dcc0af
