### ISSUE TITLE
[Bug?, Suggestion] Critical Hits and Fails

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#149]
[As per request, I transfer my message over from r/SagaEdition individually.]
It appears critical hits are not calculated automatically, regardless of weapon. As I understand, this feature is not yet in? 

And as a suggestion, it really helps to distinguish critical hits and fails in chat by adding colour coding to it (the usual way to do it is green for nat 20, red for nat 1, but I think it is better to also include a setting to change colors in case of color blindness)

And, maybe, the same can be done for the highest/lowest numbers on other dice, but it is of much less importance.

**Comment by kypvalanx** [comment]
did a little research today into colorblind design.  as of today crits and fails add a CSS class already, i can just use that class to add a read shape or a green shape.  now i have to find success and failure shapes that find around or after numbers

**Comment by LeKopic** [comment]
I think certain shapes will work for colourblindness and crits. For example. classical ! and x shapes. Or if you want to get more fancy, you can try using those:
https://game-icons.net/1x1/delapouite/dice-twenty-faces-twenty.html
https://game-icons.net/1x1/delapouite/dice-twenty-faces-one.html
Or as a simple and elegant solutions - just write Critical Fail and Critical Success in chat messages.
Maybe like that 
![image](https://user-images.githubusercontent.com/42682507/166505728-e2a1ccbc-7aef-43bd-a83c-4b08ff0e981b.png)
