### ISSUE TITLE
[Suggestion] Diagonals

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#150]
[As per request, I transfer my message over from r/SagaEdition individually.]
Per RAW, SWSE counts every diagonal as 2 squares, but maybe in addition to that there should be an option to set it to PF-like diagonal system (1-2-1-2). This homebrew appears to be included quite often.

**Comment by Orkah** [comment]
I agree with this, I normally use it as well on tabletops.
It could be a nice feature in the future.

**Comment by LilLiteralist** [comment]
Thirded.
Right now, the diagonals appear to be 1 for every diagonal.

**Comment by kypvalanx** [comment]
I also personally use this one.  it'll be added when i'm ready for homebrew settings.
