### ISSUE TITLE
[Suggestion] An option for a GM to ignore prerequisites

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#152]
[As per request, I transfer my message over from r/SagaEdition individually.]
Sometimes, as a GM you want to give bonus feats, cut some corners while creating an NPC or homebrew a bit, so enforcing prereqs is a bit counterproductive.

**Comment by LilLiteralist** [comment]
I will second this request. For instance, using the Bonus Class Talents homebrew rule (you can look it up on the wiki if you're curious). Or in Dawn of Defiance, when Force-sensitive PCs are given an extra Force power.

**Comment by kypvalanx** [comment]
would it make sense to add traits to the traits compendium that grant an additional +1 item? ie:
GM bonus Feat
GM bonus Talent
GM bonus Forcepower

**Comment by LeKopic** [comment]
Oh, yes, definitely. Feats, Talents, Force Things, HP, Trained Skills, Skill modifiers, Class Skills, and ability scores.

**Comment by kypvalanx** [comment]
https://swse.fandom.com/wiki/Bonus_Class_Talents

should there be a special bonus talent that uses these rules specifically?

**Comment by Orkah** [comment]
I agree with LeKopic, and it should be simple and intuitive as you described.

**Comment by kypvalanx** [comment]
I've expanded the choice system to handle a new Trait called "GM bonus" that will check a list of available bonuses and let you select them.

so far it just does class skills, HP and general feats, but that was just my initial testing group.
