### ISSUE TITLE
[Suggestion, Bug] Current Shield level field, srRating attribute possible issue and current shield level as status effect

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#153]
[As per request, I transfer my message over from r/SagaEdition with each request individually.]
1) It appears that Shield Generators, at least droid generators, add srRating instead of shieldRating, so Shield Value doesn't change
2) An empty field for current shield level
and/or
3) A shield status effect icon, something like that:
![unknown](https://user-images.githubusercontent.com/42682507/160167236-21cee63d-43e5-441d-bc0e-2ef2866ce5f6.png)
![unknown](https://user-images.githubusercontent.com/42682507/160167557-7f877ee5-5c4d-46af-9704-e67af9d6a73b.png)

**Comment by LeKopic** [comment]
As a side-note, in our games we use this module https://foundryvtt.com/packages/statuscounter to keep track of ammo and shield ratings, quite handy.

**Comment by kypvalanx** [comment]
shield generators add the right attribute now as part of another issue.  definitly needs a second field for tracking current level.  the  token system is still a bit of a mystery to me so we'll see about the status effect overlay

**Comment by kypvalanx** [comment]
thoughts about this as a future enhancement,  a shield icon indicating that a shield is activated, and a second health bar in the token hud.  i don't see a way to show a number on the condition icon without saving one for each number idk, maybe a custom impl could draw it.

**Comment by LeKopic** [comment]
Hm, I don't think a number is that important to be shown on a token + some GMs might want to not share that information with their players.
As an alternative to numbers, it might be possible to do it in 25% increments on an icon, something like that:
![image](https://user-images.githubusercontent.com/42682507/172025272-30e9206d-34ae-4f6e-b606-3f5a058e5d22.png)
or with percents on them:
![image](https://user-images.githubusercontent.com/42682507/172025322-f4cadbf6-cf7f-4ddf-ae58-36556ea638ff.png)

**Comment by kypvalanx** [comment]
are you a graphic dev by chance?  these look pretty good.
i think this would look pretty good actually.  i can provide an option in settings to either show that a shield is up, or show the level of shield to the 25% mark.  that prevents me from having to make this too specific.

**Comment by LeKopic** [comment]
Nope, just some paint.net and icons from Game-icons + grabbing ideas from various rpgs and ttrpgs.
If a toggable button is possible - it would be perfect, versatility and options are always good.

**Comment by kypvalanx** [comment]
give my new condition track a go, it ties condition to token effects.  i'm thinking this would work in a similiar way.
