### ISSUE TITLE
[Bug] Incorrect Defense Scores for Prestige Classes

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#160]
It appears that Jedi Knight, Jedi Master, Force Adept, Force Disciple, Sith Apprentice, Sith Lord, Droid Commander, Military Engineer and Imperial Knights have only 1 of their defenses in Class Attributes. 
![image](https://user-images.githubusercontent.com/42682507/161355115-d2e44e08-3d20-4532-9428-bfffd977e8da.png)
Probably has something to do with how the wiki (or any other source) has been parsed.

**Comment by Orkah** [comment]
I've commited a fix for that, just now.
Thanks again for pointing it out!

**Comment by kypvalanx** [comment]
made some progress on this, coming soon

**Comment by kypvalanx** [comment]
fixed in 0.5.18
