### ISSUE TITLE
[Bug][0.5.3][V9] Missing Items - Implants & Bio-Implants

### ISSUE THREAD

**Issue by Orkah** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#161]
https://swse.fandom.com/wiki/Implants

The compendium is missing those 3 implants;

https://swse.fandom.com/wiki/Nerve_Reinforcement_Implant
https://swse.fandom.com/wiki/Regenerative_Implant
https://swse.fandom.com/wiki/Sensory_Implant

I will try add them to the swse-items.db tomorrow and commit it to my current pull request.

**Comment by Orkah** [comment]
All the Bio-Implants are missing as well.
https://swse.fandom.com/wiki/Bio-Implants

**Comment by Orkah** [comment]
Note - More Missings Items

https://swse.fandom.com/wiki/Automated_Sentry_Gun (Active and Static Defenses)
https://swse.fandom.com/wiki/Energy_Shields (Light, Medium & Heavy Armors)

I'll add them shortly, I need it to finish my RollTable per items type.

**Comment by kypvalanx** [comment]
added the link for bio implants.  
fixed table parsing to find the missing implants.  
Sentry guns will be added as units and not as items since they need to be able to have a token.  they should also fit in inventory, so i'll figure that out
energy shields can be done today i think

**Comment by kypvalanx** [comment]
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/tree/0.5.19
