### ISSUE TITLE
[Bug] Penetrating Attack prerequisite

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#162]
It seems that Weapon Focus doesn't fullfil prerequisite for Penetrating Attack. Tested with Exotic Weapon Focus (Amphistaff in this case) and with Adv.Melee Weapons
![image](https://user-images.githubusercontent.com/42682507/161608391-b9bb394c-fb07-449f-b93d-07161e865e15.png)

**Comment by kypvalanx** [comment]
Payload feats take some special work on my end (ie. Feats where you make a choice). I'll take a look one the latest overhaul is stable

**Comment by LeKopic** [comment]
> Payload feats take some special work on my end (ie. Feats where you make a choice). I'll take a look one the latest overhaul is stable

Hm, the simplest way for now would be to disable prereqs for it or to just give a warning "You might not have necesarry prerequisites, but the feat will be added anyway". At least Penetrating Attack doesn't affect anything in the character sheet, I believe.
