### ISSUE TITLE
[Bug] Targeting

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#163]
Foundry's select target feature, it appears, breaks range table in Actor's sheet. I think it is intended for Foundry and the system to autocalculate range penalties, but it doesn´t work.
In the picture the target is 59 squares away, which should provide a minus 2 penalty. Tested with various distances and weapons - same issue.
![image](https://user-images.githubusercontent.com/42682507/162581328-e330e79b-fa0a-4820-b817-629741c2e371.png)

**Comment by kypvalanx** [comment]
foundry's targetting should not auto select the correct range when attacking, but still allow the user to override that
