### ISSUE TITLE
[Issue/Suggestion] Double and Triple Attack and many limbs

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#165]
It appears that a character can make a double or triple attack only with the same weapon they've attacked before, but RAW you can choose any weapon they are armed with: "If the character is armed with more than one weapon (or uses a double weapon), they may choose which weapon (or weapons) they will choose to make each extra attack."
![image](https://user-images.githubusercontent.com/42682507/162581865-4017cbee-0cb0-410b-aa98-aefca7fc658a.png)

**Comment by kypvalanx** [comment]
that wouldn't be using the double attack feat though, it would be using the dual weapon mechanic which uses a different modifier.  using the double weapon feat incurs a penalty.  the options being disabled here are to reduce that penalty.

**Comment by kypvalanx** [comment]
i'll change the label to be more clear, those are from using the double attack and triple attack feat and are not affected by the rules you quoted.

**Comment by LeKopic** [comment]
> that wouldn't be using the double attack feat though, it would be using the dual weapon mechanic which uses a different modifier. using the double weapon feat incurs a penalty. the options being disabled here are to reduce that penalty.
Are you sure that wouldn't be the double attack feat?
https://swse.fandom.com/wiki/Full_Attack#Double_Attack_and_Triple_Attack
Here it is listed under those two feats.

**Comment by kypvalanx** [comment]
so, the answer is that it does technically work, but then if you're making 2 attacks you're incurring the dual weapon penalty and the double attack penalty, if you're just gaining a second attack from dual-wielding you only incur the first penalty.  i've disabled options to reduce the number of penalties incurred.  if i've misunderstood how these penalties work though, please tell me, i just used the example where they maximised the number of attacks taken using dual weilding and double attack as reference.

**Comment by LeKopic** [comment]
Ok, after thinking some more about that.
Character without any feats makes 2 attacks with 2 weapons (or a double) - minus 10 to hit on all
Character with Dual Weapon Mastery I, 2 attacks, 2 weapons - minus 5 to hit on all, but he must use both weapons or both ends of a double weapon
Character with Double Attack, 2 attacks, 2 weapons - minus 5 to hit on all attacks, but he can either attack with both weapons, or with the same weapon twice


Plus, a character can get Dual Weapon Master I much, much earlier than Double Attack, but Double Attack is kinda more useful (for example, wielding a gun and a knife, you can choose to attack twice with a gun, or to attack twice with a knife, or to attack once with a gun and once with a knife. Or just have something in your other hand, like a comlink)

And if you want 3 attacks, one standard, one from double attack and one from using double weapon or two weapons - the character will get a huge penalty (depending on the feats).

At least I think that's how it works?

**Comment by Orkah** [comment]
This might help understanding the mecanics from "DMFs Big List of SWSE NPCs"
![DualWeaponMasterJedi](https://user-images.githubusercontent.com/10533768/164990293-2aea3d2a-b4ce-4a6d-a05e-af985b5c8967.png)

**Comment by LeKopic** [comment]
> Plus, a character can get Dual Weapon Master I much, much earlier than Double Attack, but Double Attack is kinda more useful (for example, wielding a gun and a knife, you can choose to attack twice with a gun, or to attack twice with a knife, or to attack once with a gun and once with a knife. Or just have something in your other hand, like a comlink)

Also, there is an important difference - Double Attack works only with one group or one exotic weapon, while dual-wielding works without such restrictions.

**Comment by kypvalanx** [comment]
you would still take the dual-wielding penalties in those cases though because you're still using multiple weapons.  is that not the case?

**Comment by LeKopic** [comment]
Nope, I am pretty sure you won't. 
For example, if you have Double Attack and you take two attacks with two separate weapons, the penalty will be only -5.
But if you have Double Attack and you want to take three attacks (lets say, once with right hand, twice with left hand), the penalty wiil be -15 (-10 from additional attack from dual wieding, -5 from additional attack from DA)
If you have Dual Weapon Master I and Double Attack, then the penalty for 3 attack will be -10 (-5 from DA, -5 from dual wielding)
Essentially, it is not dual wielding that gives a penalty, but an additional attack.

I hope I got everything correct, I am a bit tired, but it should work like that. It is a VERY niche and rare thing, but still

**Comment by kypvalanx** [comment]
i think i follow.  i see where i made a bad assumption.  this should be fixed for the next enhancement release.

i'm linking this because it includes additional feats and talents i should be supporting here:
https://www.reddit.com/r/SagaEdition/comments/8o0kan/full_attacks_dual_weapon_mastery_double_attack/

**Comment by kypvalanx** [comment]
also, if any of you have a better idea for the full attack screen, by all means.  i'm not tied to the current layout

**Comment by Orkah** [comment]
We should make it compatible with https://foundryvtt.com/packages/token-action-hud/

They have instruction on how to integrate with it here : 
https://github.com/Drental/fvtt-tokenactionhud/blob/master/adding_systems.md

It would be much smoother to request or make roll with that awesome modules.
Tell me what you think.

**Comment by LeKopic** [comment]
![image](https://user-images.githubusercontent.com/42682507/164994142-59252d67-ec97-4dd5-8189-21a4705397ba.png)
I was thinking along those lines. Maybe make the system check which of the feats/talents the character has and provide relevant buttons? Or, maybe a dropdown list? 

P.S. Also, don't look at the range numbers, I homebrewed and halved them all except for thrown weapons.

**Comment by LeKopic** [comment]
And a second idea, but I am not really sure it is doable with foundry or if there is an easy way: saving attack presets. Choose attacks, choose modifiers, save them as a preset, use them again later.
![image](https://user-images.githubusercontent.com/42682507/164994399-140a25a3-20f8-4464-a2f8-5329a33c158b.png)

**Comment by kypvalanx** [comment]
i was going to add relevant feats when i got to it.  probably soon.  as far as the presets go, that's totally doable, my plan was to let you create a macro bar button from a configured full attack, but I kinda like this way too.

**Comment by kypvalanx** [comment]
New design for resolving what attacks are allowed.

# Design:

## Simple Attack
* requires that fewer than 2 simple attacks have been selected
* can select 1 or 2
* if 2 are selected, apply dual weapon modifier

## Double Attack Feat
* requires 1 or more simple attack to be selected
* can select 1
* if 1 is selected apply multi attack modifier

## Triple Attack Feat
* requires 1 double attack to be selected
* can select 1
* if 1 is selected apply multi attack modifier

## Multi Attack Modifier
* -5
* can be reduced with Multi attack proficiency (multiAttackBonus)

**Comment by LeKopic** [comment]
> ## Simple Attack
> * requires that fewer than 2 simple attacks have been selected
> * can select 1 or 2
> * if 2 are selected, apply dual weapon modifier

One small addition - not necessarily 1 or 2, some characters have more arms/appendages than 2, especially droids. So they can make the same amount of attacks with a wider variety of weapons.

**Comment by kypvalanx** [comment]
I don't think that it grants them additional attacks.  not according to the wording of extra arms on the different species anyway

> Extra Arms: Male Besalisks have four arms, and female Besalisks can have as many as eight arms, this means a Besalisk can hold up to four (males) or six (females) items or weapons at a time. **This ability does not grant extra attacks; however, it does mean a Besalisk can wield two (males) or three (females) two-handed weapons at a time.**

**Comment by LeKopic** [comment]
> I don't think that it grants them additional attacks. not according to the wording of extra arms on the different species anyway

You are right, but:
For example, you have double attack and want to do 3 attacks. Penalty will be huge, but you can do it. You can make each of those attacks with a different weapon.

**Comment by kypvalanx** [comment]
fixed in 0.5.4

**Comment by kypvalanx** [comment]
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/0.5.4
