### ISSUE TITLE
[Suggestion] Encumbrance, Gravity

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#166]
1) Currently, there is no way to easily track current weight the character has in their inventory. I suggest adding: weight counter in Equipment tab, Heavy Load and Carrying Capacity calculated values (in Equipment tab), Heavy Load and Carrying capacity automatically applied penalties (+ Spacehound talent, if the character has it). 
2) Gravity effects on Encumbrance, relevant Skill Checks and Attack Rolls. Maybe it is better to do it like Character Condition in the Summary Tab, right under Portrait?
![image](https://user-images.githubusercontent.com/42682507/164995179-4fed3b70-baa1-4ce4-9b48-4c53f7c873ec.png)

**Comment by kypvalanx** [comment]
rule reference https://swse.fandom.com/wiki/Encumbrance

do you have a reference to the gravity multiplier?  i don't see it on this page.

**Comment by LeKopic** [comment]
https://swse.fandom.com/wiki/Gravity

**Comment by kypvalanx** [comment]
I like your design for the gravity selector.  i'll add a weight readout and a total encumbrance readout on the equipment tab, and a warning on the top bar that your character is encumbered.  then i need to tie the listed things in.
