### ISSUE TITLE
[Suggestion] Showing Flat-Footed Reflex Defense. Also, wealth.

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#167]
As the title says. During combat it is slightly faster to just open the character sheet and see the value there than calculate it in your head every time.
Suggestion one: collapseable row. By pressing on the button (folder button in that case, just a placeholder) a new row appears below Ref row. 
![image](https://user-images.githubusercontent.com/42682507/164995729-d38d3a84-0c2a-47d9-bd1f-f7f90ec5dc73.png)
Suggestion two and thrree: either a collapseable row or just having it all times, but maybe with a smaller font/size of the row? 
![image](https://user-images.githubusercontent.com/42682507/164995784-f915306d-9f27-4528-8b33-30dcfb1b010a.png)
Or
![image](https://user-images.githubusercontent.com/42682507/164995825-487d72e0-3586-4332-baef-82e1e7f83070.png)

And as a side-note, a row for character's wealth/current money would be nice. Maybe in Equipment tab or in the Summary.

**Comment by kypvalanx** [comment]
wealth system added by #173 

adding a link to Flat-footed reference here for reference:
https://swse.fandom.com/wiki/Initiative_Order

**Comment by kypvalanx** [comment]
I'd like to compliment your enhancement request btw.  you provided a UI design for a backend dev whose been struggling to develop UI.  i intend to take classes eventually, but i have not yet.
