### ISSUE TITLE
[Bug] Portrait extends downwards too far

### ISSUE THREAD

**Issue by LilLiteralist** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#169]
If the avatar is taller than it is wide, it will extend down into the "Conditions" text field.
![image](https://user-images.githubusercontent.com/104447108/165382229-902d0eb5-9fc0-461e-84d6-15c5b1357090.png)
I haven't tested to see what happens if the portrait is wider than it is tall.

**Comment by kypvalanx** [comment]
051cc7bea867935b039992294cf8e01a225b9817
