### ISSUE TITLE
[Bug] Existing PC Sheets can no long be opened

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#175]
After update to 0.5.5 from 0.5.3, the existing PC Sheets can no long be opened with following error message.
![image](https://user-images.githubusercontent.com/22677493/166217410-42d983dd-8127-48ab-bea4-af7753f871e2.png)

**Comment by sanpats** [comment]
[fvtt-Actor-xander-holwal.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/8602125/fvtt-Actor-xander-holwal.zip)
one of the actor that cause error.

**Comment by LeKopic** [comment]
Just checked, I have the same issue on my end too. I think there might be something wrong with compendium and/or actor sheet?

**Comment by kypvalanx** [comment]
this should now work in 0.5.6

**Comment by sanpats** [comment]
0.5.6 still bugged on some characters.

**Comment by sanpats** [comment]
[fvtt-Actor-larov-stefanov.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/8605521/fvtt-Actor-larov-stefanov.zip)

**Comment by sanpats** [comment]
0.5.9 still bugged.

**Comment by kypvalanx** [comment]
> 0.5.9 still bugged.

i appreciate the character sheet as reference.  0.5.10 should work for that sheet

**Comment by kypvalanx** [comment]
I think this issue is resolved, but I'm leaving this issue open until I get affirmation.

**Comment by sanpats** [comment]
I believe it's fixed too.
