### ISSUE TITLE
[Bug] Incorrect Actor Sheets

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#183]
Some Actor Sheets are bugged for some reason. For example, this sheet doesn't have Attacks, Skills, Defenses and HP set up. The actor was made on one of the previous versions.
![image](https://user-images.githubusercontent.com/42682507/166448178-9fb7f94d-68ce-45a6-8eb4-a057f05968cb.png)
![image](https://user-images.githubusercontent.com/42682507/166448246-c6be0119-51c5-47a7-8fcf-fd67dd01127b.png)

Here is his sheet. 
[fvtt-Actor-count-dooku.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/8610230/fvtt-Actor-count-dooku.zip)

**Comment by LeKopic** [comment]
Dooku and almost every other actor is fixed after the latest update, but two player-droids are broken in similar way
![image](https://user-images.githubusercontent.com/42682507/166491643-485237cb-0a09-4426-8515-106659e001ac.png)

[Droids.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/8611867/Droids.zip)
![image](https://user-images.githubusercontent.com/42682507/166491591-3ed861ba-6672-49c0-bf56-1010964e3c46.png)

**Comment by kypvalanx** [comment]
ah, looks like another brittle prerequisite block.  the attribute update broke prereqs a bit.

**Comment by kypvalanx** [comment]
I think this issue is resolved, but I'm leaving this issue open until I get affirmation.

**Comment by LeKopic** [comment]
Yes, I believe this issue is now resolved, but I've opened #187 with a different open.
