### ISSUE TITLE
[Bug] Cannot fire vehicle's weapons

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#185]
As the title says, imported a vehicle from compendium, when I try to attack:
![image](https://user-images.githubusercontent.com/42682507/166492059-779f3605-3978-43b1-8e4f-c806737e12b7.png)
Also, Full Attack is empty
![image](https://user-images.githubusercontent.com/42682507/166492102-c32db823-d1a0-4132-88be-ef23f466f3ac.png)

**Comment by kypvalanx** [comment]
is this attacking from the pilot's sheet or the vehicle's sheet?

**Comment by LeKopic** [comment]
Vehicle's sheet

**Comment by kypvalanx** [comment]
I think this issue is resolved, but I'm leaving this issue open until I get affirmation.

**Comment by LeKopic** [comment]
Yep, just checked on the new version, it works
