### ISSUE TITLE
[Bugs] Independent Droid Prerequisites, Feat prerequisite, 

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#191]
1) Independent droid prestige class cannot be added because the system doesn't recognize installed Heuristic Processor.
2) Kinda the same thing happens with Droid Shield Mastery feat. The system doesn't understand items Shield Generator (SR5) or Shield Generator, although it did understand Shield Generator in 0.5.3.

**Comment by kypvalanx** [comment]
#131
