### ISSUE TITLE
Attribute calculations not accepting positive modifiers

### ISSUE THREAD

**Issue by magee101** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#195]
When the sheet calculates HP (or other modifiers based on an Attribute's modifier score); it ignores a positive value but accepts a negative value. For example; a character with a 2 Con modifier does not get +2 added to their total hp; the positive value is ignored (though recorded in the class tab). Meanwhile; a character with a -1 Con Modifier is correctly receiving a -1 to their total hp per level). Please see the attached images for examples.

Possible Error/Solution: I believe that the system is recognizing the negative application because of the - symbol; however since the positive integer does not have a + symbol it is not recognizing it as something to add; if one could add a + in the Mod value box in the Attributes section; it may calculate correctly. So far I have not been able to find where I can edit the sheet to do such a thing to verify if this solution fixes the problem. 
![image_2022-05-12_200851669](https://user-images.githubusercontent.com/83249744/168191514-3dfb8607-8148-4414-ac91-86a25302bcb6.png)
![Negative Con Mod](https://user-images.githubusercontent.com/83249744/168191604-f1b199be-e57a-478e-8ae8-f7cc8f67fd03.JPG)

**Comment by LeKopic** [comment]
Which version are you using? If 0.5.15 - hp is calculated ok. 
![image](https://user-images.githubusercontent.com/42682507/168259280-761ca262-4dde-485b-9dd4-374cccfa3e5b.png)
If some previous version, like 0.5.3 - see #155 - https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/issues/155#issuecomment-1086297056

**Comment by kypvalanx** [comment]
I'll double check latest either way. let me know if bumping to latest fixes your problem

**Comment by magee101** [comment]
Hey thanks! I didn't realize there was an updated version; updating did indeed fix the HP calculation bug; thanks guys/gals.

**Comment by kypvalanx** [comment]
awesome! glad you got it working.
