### ISSUE TITLE
[Bug 0.5.15] Feats and Talents

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#196]
If you add a soldier class (either as the first class or down the line) the armor proficiency feats are a bit strange: 
![image](https://user-images.githubusercontent.com/42682507/168260061-b42a76ba-f1e6-4788-8e19-09817eb1195d.png)

Prestige Classes, I think, break talents too:
![image](https://user-images.githubusercontent.com/42682507/168260333-886d9ef3-fa24-46e5-b738-509d00dc5d2e.png)
![image](https://user-images.githubusercontent.com/42682507/168260421-02e65923-fd21-4f90-996b-62d5b9af91b6.png)

**Comment by kypvalanx** [comment]
looks like a side effect of the payload overhaul.  the armor proficiency feats were the first feats to use the old system and there was definitely some custom code specifically tailored to that.  i'll take a look today
