### ISSUE TITLE
[Suggestion] Manual Override

### ISSUE THREAD

**Issue by magee101** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#197]
Would it be possible to get a manual override mode/option for the character sheets; so that feats and talents can be added to the character sheet even if it thinks the choices are illegal? Would be a good work around for ongoing campaigns should an update bork something.

**Comment by LeKopic** [comment]
I believe it is WIP as of #152.

**Comment by kypvalanx** [comment]
that can now be done using the GM Bonus Trait https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/issues/152#issuecomment-1121409057
