### ISSUE TITLE
Jedi Class should start with a lightsaber.

### ISSUE THREAD

**Issue by jasony1974** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#2]
Jedi class should start with a lightsaber as starting equipment.

https://swse.fandom.com/wiki/Jedi#lightsaber

**Comment by kypvalanx** [comment]
the easy way to do this would be to just add a standard lightsaber.  the hard way would be to provide a dropdown of all lightsabers in the compendium.  i think the latter will also add functionality that's important for other future features so i'll go that way.

**Comment by jasony1974** [comment]
Ok, you understand your design better than I do. But at level 1, per the core rule book, a new Jedi would only have access to a lightsaber provided by his master, which I would assume would be a “basic” lightsaber.

**Comment by kypvalanx** [comment]
that's a good point, i suppose, worst case, the player can change items.
