### ISSUE TITLE
[Issue 0.5.16] Flat-Footed Calculation 

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#200]
Right now Flat-Footed works correctly only if Dexterity Bonus is >= 0, but if it is less than 0 the system still removes the penalty.
![image](https://user-images.githubusercontent.com/42682507/168400757-2cbcd68b-244a-480e-9014-2c09fcf83a4d.png)
I think it can be fixed easily by something like that: if dexterityBonus >= 0 - replace the bonus with 0, but if dexterityBonus < 0 - nothing changes.

**Comment by kypvalanx** [comment]
i found 2 mentions of flat footed, only one clearly states that FF includes negative DEX mods.  thanks for pointing this out.
