### ISSUE TITLE
[Minor Issue] GM Bonus Trait amount

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#202]
When I add a new GM Bonus, the system promts me to enter the value of the bonus, but it always assigns a 1.
![image](https://user-images.githubusercontent.com/42682507/168418272-1a2f636a-4cb4-4e84-8517-94a42e8488cf.png)
Not a big deal, can be easily fixed manually by changing it in Attributes tab of a trait.

**Comment by kypvalanx** [comment]
I cannot reproduce this in  0.5.18

**Comment by LeKopic** [comment]
Issue is resolved in 0.5.18.
