### ISSUE TITLE
[Minor bug] Adding Jedi Class as the first class

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#203]
When adding Jedi class as the first one, it shows up like that - 
![image](https://user-images.githubusercontent.com/42682507/168418904-d5365108-a992-4626-b8d9-3aba24f16f9c.png)
After adding it the second time there is a prompt to pick one of the feats (although every base feat from the class is picked). Not a big deal and, I think, the issue only exists with the Jedi class because it provides a lightsaber.

**Comment by kypvalanx** [comment]
so the bug is entirely what changed that made the lightsaber "choice" appear as a suffix.  after it checks if it's the first class being added it checks for another class by that name.  and here i though the new payload system was clever

**Comment by kypvalanx** [comment]
fixed in 0.5.18
