### ISSUE TITLE
[Bug 0.5.17] Prestige Class Missing Talents (and other things)

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#204]
Well, the screenshot speaks for itself:
![image](https://user-images.githubusercontent.com/42682507/168419138-373b3533-d06f-4a29-8f1b-7f4ddba4d6af.png)
I think Prestige Classes don't add anything to actors: talents, defense bonuses, Force Techniques, class abilities.

**Comment by kypvalanx** [comment]
i can't reproduce it in 0.5.18.  are there any errors in the logs?

**Comment by LeKopic** [comment]
I'll check it on 0.5.18 in several hours.

**Comment by LeKopic** [comment]
Ok, it appears the issue is with actors made in older version, not the system. After removing prestige classes and readding them - everything works just fine.
