### ISSUE TITLE
[Issue] Dodge bonus and Flat-Footed

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#206]
There are several things that add bonusDodgeReflexDefense. According to wiki:
Special: A situation that makes you lose your Dexterity bonus to Reflex Defense (if any) also makes you lose any dodge bonuses.
(https://swse.fandom.com/wiki/Martial_Arts_I)
Right now, Flat-footed includes any dodge bonuses present (such as from Martial Arts I).

**Comment by kypvalanx** [comment]
i thought so, hence why it's a different bonus, i just couldn't find the rule for it.

**Comment by kypvalanx** [comment]
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/tree/0.5.19
