### ISSUE TITLE
[Bug] Cannot add some talents

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#207]
I tried to add Weapon Specialization and Greater Weapon Focus to a character, both times it produces the same error:
![image](https://user-images.githubusercontent.com/42682507/168446708-7edf28d6-dcab-4c68-b716-6bdcaec1d7aa.png)
I think something is wrong with payload?

**Comment by kypvalanx** [comment]
there's apparently an attribute value that is not a string

**Comment by kypvalanx** [comment]
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/tree/0.5.19
