### ISSUE TITLE
[Bug] Autofire and Critical Hits

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#212]
It seems the system doubles the damage when a character is using Autofire.  Critical hit on Autofire deals normal damage.

**Comment by LeKopic** [comment]
Speaking about critical hits, how are they doubled? It seems a bit strange. Are the dice doubled, not the result?
![image](https://user-images.githubusercontent.com/42682507/169119407-0a3a6959-622b-42aa-bd71-1117acc7a927.png)

**Comment by kypvalanx** [comment]
yes, the dice are doubled. you roll more dice for a crit.  is that not how that works?  i might have migrated that from another system accidentally

**Comment by LeKopic** [comment]
It deal twice amount of dice in the majority of other d20 systems, like PF or dnd 3.5e, I believe, but in SWSE raw - it just doubles it. But it can certainly be a homebrew option in the future.
