### ISSUE TITLE
[Bug?] Attack Macro

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#213]
Neither my players nor I can drag and drop macros for attacks after one of the latest updates. 
Is it possible to make something like that?
![image](https://user-images.githubusercontent.com/42682507/169023987-eb751521-3077-49cf-b701-e84679c3df1a.png)

**Comment by kypvalanx** [comment]
yes, that can be added.
