### ISSUE TITLE
[Suggestion] Force Power Tracking

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#214]
Currently it is not easy to keep track of Force Powers (especially for the GM if there are quite a few force users). Maybe something like checkboxes can used to track used Powers?
![image](https://user-images.githubusercontent.com/42682507/169120479-96fc1a23-1c57-4652-a006-feb6938fd930.png)

**Comment by kypvalanx** [comment]
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/0.6.16

this has been released
