### ISSUE TITLE
[Bug?] Applying Templates

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#219]
Not sure if applying templates is already implemented or not, but if they are:
1) I cannot apply templates to unequipped weapons/armor at all, when I drag and drop - nothing happens. No errors in console either.
2) When I try to drag and drop template on equipped items - the system sais that I miss the prerequisites.
![image](https://user-images.githubusercontent.com/42682507/169543277-7ce53d2b-d55c-424d-b31b-cd8207298458.png)
2.1) If I try to apply an armor template it lists slightly different prerequisites and I am concerned that it might be requiring both of those prereqs be fullfilled, which is impossible:
![image](https://user-images.githubusercontent.com/42682507/169543628-a82f7df6-e96f-49cc-9d65-f1c4839a60a1.png)

**Comment by LeKopic** [comment]
Ah, ok, I wasn't aware of that. Yeah, after checking it with the method you described - it works.

**Comment by kypvalanx** [comment]
i'm reopening this to take a look at making that system more intuitive

**Comment by LeKopic** [comment]
Suggestions:
1) Allow to drag a template to an unopened item + a short instruction somewhere (maybe even the name of the compendium "Templates (drag and drop on item)".
2) A dedicated button in Equipment screen.
![image](https://user-images.githubusercontent.com/42682507/170347498-1116b8f4-08fd-4d03-a6a1-ef46e70b251f.png)
Clicking on it opens a popup window akin to, for example, Weapon Focus feat or Exotic Weapon Proficiency, but it lists all the equipment it can be applied to. Pro - really user-friendly. Con - might be too much to scroll through if there are too many applicable items.
3) A dedicated button somewhere in item editing screen:
![image](https://user-images.githubusercontent.com/42682507/170348749-1518bf05-42a1-42bc-8b5f-d2a35f8eb336.png)
4) Or just the same window that asks for an item to be modified as in 2), but on dragging and dropping the template into the equipment tab.
![image](https://user-images.githubusercontent.com/42682507/170349324-e22ff490-3d39-4a7a-a839-c2f9083af63c.png)

**Comment by kypvalanx** [comment]
currently templates are on the modifications tab, should i rename the tab to "Modifications & Templates" ?

**Comment by LeKopic** [comment]
Hm, no, it would take too much space. 
It can be done as a completely separate category in Modifications tab though.
Something along those lines, maybe?
![image](https://user-images.githubusercontent.com/42682507/170540665-5454447c-e1a9-4fe2-a5c4-bfd53331600d.png)

Also, do standard upgrades work? I am unable to apply Trageting Scopes or any other available upgrades + some upgrades are just missing from Items compendium.

**Comment by kypvalanx** [comment]
> Also, do standard upgrades work? I am unable to apply Trageting Scopes or any other available upgrades + some upgrades are just missing from Items compendium.

templates got TLC recently, i didn't touch standard mods.  sounds like something to do over the long weekend

**Comment by kypvalanx** [comment]
how this currently works is that a template has to be added to an actor first, and then applied to a given item on that sheet.  the problem is that items that are not on an actor, cannot be modified in this way.

items can accept ActiveEffects.  i will be modifying the ondrop method for items onto items to create an equivalent activeEffect rather than a link to an item on a parent sheet.  this should do quite a bit to simplify code and make it possible to modify unaffiliated items.
