### ISSUE TITLE
 [BUG] Armor Penalty and Vehicle Weapon Bug

### ISSUE THREAD

**Issue by xBassimon** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#222]
1.) the -5 penalty for wearing medium armor ist still applied even if the actor has the appropriate proficiency
![image](https://user-images.githubusercontent.com/106470561/170862559-902c5d84-7438-4f3a-a48b-542f713a51d9.png)
![image](https://user-images.githubusercontent.com/106470561/170862574-a8a8726c-5c51-4aee-81c8-fafaaac22ab4.png)
![image](https://user-images.githubusercontent.com/106470561/170862583-a18ac713-7210-4892-a58b-61fa96d7b7ec.png)
2.) Since some update a while ago the weapons in vehicles aren´t displaying any values and therefor cant be rolled
![image](https://user-images.githubusercontent.com/106470561/170862633-728b3f47-724d-45f9-8453-55046a28c1b7.png)

Thank you for your work! My players and me are really enjoying the system.

**Comment by LeKopic** [comment]
1. Can confirm, I have the same problem.
2. Same, but can be fixed if you put a character into a slot in Stations tab of a vehicle. If you want to use vehicles now - create dummy vehicle crew mates (https://swse.fandom.com/wiki/Crew_Quality) and fill the slots. Or my quick and dirty method - copypaste the whole statblock from the wiki to Notes section.

**Comment by kypvalanx** [comment]
> Same, but can be fixed if you put a character into a slot in Stations tab of a vehicle. If you want to use vehicles now - create dummy vehicle crew mates (https://swse.fandom.com/wiki/Crew_Quality) and fill the slots. Or my quick and dirty method - copypaste the whole statblock from the wiki to Notes section.

lol, what?  that is the weirdest workaround

**Comment by kypvalanx** [comment]
oh, it's a workaround for the second issue, got it.  that actually kinda tells me what the problem is.
