### ISSUE TITLE
[Suggestion] New Trait - Squad

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#223]
Rule reference - https://swse.fandom.com/wiki/Squads https://swse.fandom.com/wiki/Packs_and_Swarms

Creating a squad right now is a bit lengthy process in the system, done by adding and tweaking several traits. New trait (if trait is the best way to do it, I am not sure) "Squad" might streamline it quite a lot because it just makes straigthforward changes:
1) Increases size by one step (replaces size trait),
2) Doubles the HP
3) Increases DT by 10  **_(*)_**
4) Add +4 to attacks

The only thing I have huge doubts about - increasing DT by 10.
It seems that it overrides DT increase from size increase (https://swse.fandom.com/wiki/B1-Series_Battle_Droid_Squad, https://swse.fandom.com/wiki/Shyrack_Swarm and some other statblocks), but at least one statblock says it does not override (https://swse.fandom.com/wiki/Womp_Rat_Pack)

**Comment by kypvalanx** [comment]
my day off and drunk self agrees this is a good way to achieve this.  i'm pretty sure this is a good idea on every other day.

**Comment by kypvalanx** [comment]
this is taking more work than expected, but it's expanding the system in a good way.

**Comment by LeKopic** [comment]
Hm, I don't think hitPointEq = *2 works as inteded, it doesn't multiply the HP. 
![image](https://user-images.githubusercontent.com/42682507/172028036-237dfe8b-7932-4487-a130-7b94469c5354.png)
