### ISSUE TITLE
[Bug 0.5.24] Bugged talent, cannot open actorsheet

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#225]
Problem: if I try to add a Weapon Specialization talent to an (new) actor sheet Foundry gives that error:
![image](https://user-images.githubusercontent.com/42682507/171875051-eb32561f-7913-4417-aff2-7c6793b185de.png)
And it becomes impossible to open the sheet afterwards.
As far as I can tell it is the only talent/feat that produces such error, but I don't have enough time today to test more talents. 

More details for an actor: species - human, weapon focus - Simple Weapons, Weapon Specialization - same, a knife was equipped.

**Comment by kypvalanx** [comment]
forgot a pair of "..."
