### ISSUE TITLE
Weapon attack does not appear on summary page when equipped.

### ISSUE THREAD

**Issue by Glyph-K** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#229]
When moving a weapon to the equipped field in the equip tab the associated attack does not appear on the summary tab.

**Comment by LeKopic** [comment]
Hm, try hitting F5 and checking again, it fixes that issues for an actor for me.

**Comment by Glyph-K** [comment]
A refresh of the page does fix the problem as @LeKopic said.

**Comment by kypvalanx** [comment]
that gives me a bit of a hint, and i'll take a look at this after work.  if you can export the character that's being affected and post here it'll be a lot easier.

**Comment by LeKopic** [comment]
> that gives me a bit of a hint, and i'll take a look at this after work. if you can export the character that's being affected and post here it'll be a lot easier.
[fvtt-Actor-testingweaponbug.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/8865388/fvtt-Actor-testingweaponbug.zip)
Not sure if it will help, but I have the same bug with every _new_ actor. Workflow: Create a character or NPC, add a species, go straigth to equipment, add blaster rifle, equip it, go to Summary:
![image](https://user-images.githubusercontent.com/42682507/172728191-e1110917-c9c5-424a-a6b8-ab11c4f5bccd.png)
Attacks are unchanged. It is very curious that unarmed attacks don't change too when I add a species.
No erros when I attack with Unarmed, it just don't have any bonuses and damage is 0.
Hitting the empty (blaster rifle) attack produces the error reported by Glyph-K. 
After reloading foundry - everything works.

Also, tested importing an existing "unbugged" character to a brand new actor - same issue. Maybe there is some error with how initial attacks/sheet is generated? Or, complete speculation, maybe the system/foundry cannot recheck after initial generation, so it thinks attacks are still the same?

**Comment by kypvalanx** [comment]
it's because it's trying to retrieve the actor from the system before the actor has been finalized and at that point it does not have it's items attached...
