### ISSUE TITLE
[Suggestion. Issue?] Collapseable weapons and changing fire modes 

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#244]
Right now, when I change weapon mode of fire it closes the weapon tab, which might be quite annoying (at least 1 player complained), Not sure if intended/fixable, but might be nice.

**Comment by kypvalanx** [comment]
it's not easily fixable at this time, and I also find it annoying.  right now the collapse functionality is all client-side and no state is saved. so every time the pge loads it defaults to collapsed.  changing the weapon mode causes the page to refresh.  it's fixable, but it will take a bit.

**Comment by kypvalanx** [comment]
fixed in https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/0.6.18
