### ISSUE TITLE
[Issue] Compendium Loading Times

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#257]
Yeah, as it says in the title - it taxes heavy on players' computers and it takes quite a while to load, sometimes just bricking their browsers. Not sure what's causing it, but even from GM's side it takes a second or two to load. Maybe this is due to loading a lot of items multiplied by somewhat outdated players' systems multiplied by connection issues.
I think it loads all items at once? 

On other hand - it has accelerated Foundry's initial loading time quite a lot, so that's a huge plus.

**Comment by kypvalanx** [comment]
I knew the new compendium would be slower.  I didn't realize it would be that slow.  I'm visiting family and won't update for a few days but when I'm back, I'll at least poe'st a lite version without the new compendium while I streamline it.

**Comment by kypvalanx** [comment]
performance will continue to be worked on, but for now a system toggle exists to disable the custom compendium viewer.  you need to refresh after saving the setting for it to work.
