### ISSUE TITLE
[Bug] Cannot open vehicles sheets

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#258]
I cannot open neither existing vehicle sheets nor from compendium.
![image](https://user-images.githubusercontent.com/42682507/177001518-d6e3e605-11e3-4ddd-ba7f-0894d9bb4550.png)

Also, I don't think I can import any vehicle.

**Comment by kypvalanx** [comment]
Can you export the sheet for that or is that what you meant?  If not can you describe it?

**Comment by LeKopic** [comment]
Sry, I wasn't clear
1) I imported some vehicles from the compendium to the game in one of the previous versions. Now I cannot open them and receive the errors in the screenshot. + I cannot open any vehicle sheet in the compendium
2) If I right click any vehicle in the compendium there is no "import..." option that add it to the world.

If you need any logs/files/tests - I'll be at my pc in ~8-9 hours

**Comment by kypvalanx** [comment]
I'm not near a computer until the 5th.  If you have more you think is useful I'll take it, but otherwise I won't have specific asks until I check it out on the 5th or 6th

**Comment by xBassimon** [comment]
just to let you know, i am having the same issue
