### ISSUE TITLE
[Bug] Starship skills not calculating correctly.  

### ISSUE THREAD

**Issue by Derinzed** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#259]
The piloting and initiative skills are being calculated without applying the starship size modifier.  This issue extends to both, using player crew, and the "quality crew" options

**Comment by kypvalanx** [comment]
i did a dumb https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/commit/ebed4a8526beb0939a26e7ef3d9f44315491d776
