### ISSUE TITLE
[Bug] Item Modifications return an id error

### ISSUE THREAD

**Issue by Derinzed** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#269]
Dragging the helmet package onto armor produces the following error and does not apply the upgrade to the equipment.

![image](https://user-images.githubusercontent.com/45581121/178129839-7f0b580a-1a93-4614-ab63-dcd1e721e236.png)

As an extension of this, I also noticed that custom armor cannot be applied to NPCs, I don't know if this extends to all custom items or not.

**Comment by Derinzed** [comment]
Potential fix in the latest pull request

**Comment by kypvalanx** [comment]
4757c3384d2a45e0b8f1337f815b5026c401a01a definitely fixed here and added improvements that will improve other items in the future.
