### ISSUE TITLE
[Bug]  Starship skills do not include the bonuses provided by characters equipped to station slots.

### ISSUE THREAD

**Issue by Derinzed** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#270]
Title pretty much explains it all. 

Three other side bugs/QoL requests:  You cannot add provided items to vehcileBaseType items, you cannot remove systems from starships once you've added them, and you cannot add multiple of the same systems to starships (this may be by design).

**Comment by kypvalanx** [comment]
tht should definitly work, i'll take a look.

you should only be able to add multiple gunner positions, and that should be able to be done by dragging a weapon to the right spot on that page.  i'll take a look tonight

**Comment by Derinzed** [comment]
Thanks for taking a look!  How would I add a location for gunner weapons.  If I add a turbolaser to a Colossal (Frigate) ship, it cant be moved from equipment to a gunner location, since there are no gunner weapon locations.
 
![image](https://user-images.githubusercontent.com/45581121/178365463-c7588d85-4313-43ca-b92f-aa2a28c3a5a2.png)

(ignore the ship name, I overrode it to be a heavy freighter.

**Comment by kypvalanx** [comment]
there should be a spot to drop it that creates a gunner position.  i'll take a look

**Comment by kypvalanx** [comment]
- [ ] You cannot add provided items to vehcileBaseType items
** this should not need to be done.  provided items are a way to programmatically add items to an actor from another item.  you'd want to manually add any new item.  
- [ ] you cannot remove systems from starships once you've added them 
** this is a bug
- [ ] you cannot add multiple of the same systems to starships
** definitly a bug
- [ ]  How would I add a location for gunner weapons. 
** there should be a spot to drop it that creates a gunner position. i'll take a look

**Comment by Derinzed** [comment]
Starship skills do not include the bonuses provided by characters equipped to station slots bump.
