### ISSUE TITLE
[Bug] Attack rolls are rolled twice

### ISSUE THREAD

**Issue by Derinzed** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#272]
The generateAttackCard function uses inline rolls for both attack and damage, therefor it is actually rolling the dice; however, the rollAttacks function creates a chat message of the roll type, also causing a roll to be done for attack.  This creates an inconsistency between what is displayed and what the system thinks internally regarding the critical failure and success icons.  It also means that the system is incompatible with Dice so Nice, since it generates two rolls in place of a single one.

**Comment by kypvalanx** [comment]
this has a duplicate #284
