### ISSUE TITLE
[Bug] Cannot change condition tracker

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#273]
When I try to edit condition track via an actor sheet the conditon tracker just resets to 0.
If I edit condition tracker by accessing an actor sheet through a token it lets me to set it to different number, but it does nothing and these errors show up:
![image](https://user-images.githubusercontent.com/42682507/178483509-95769167-2770-4b01-a06e-3951f3692292.png)

After changing condition tracker on a token it is no longer possible to open token's sheet:
![image](https://user-images.githubusercontent.com/42682507/178483653-61d64592-89cd-4c94-ad03-e7e5d8988e2a.png)

Except for one token, which can be opened, but (no errors in log, strangely enough):
![image](https://user-images.githubusercontent.com/42682507/178484099-4a4794f1-0665-45bd-8def-f42e7bd5660c.png)

And, also, condition icons are not resetting on a token:
![image](https://user-images.githubusercontent.com/42682507/178484391-81991f49-101c-4bd5-b969-641272cb1b38.png)

**Comment by kypvalanx** [comment]
adding link to duplicate #280
