### ISSUE TITLE
Adding compatibility to Token Action HUD module

### ISSUE THREAD

**Issue by Vaslayak** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#276]
This module seems pretty cool, you can link action, skill and ability to a bar and just use that instead of looking into your character sheet all the time :)
![Capture d’écran 2022-07-14 093049](https://user-images.githubusercontent.com/109117919/178994460-610934af-15f9-48c2-8fde-ba43a1f419d6.png)

As seens here:https://youtu.be/mB5_fsXGUSE?list=PLg8qCzR5tyvRYFezsvpUAfJYLmzuEgWrs&t=44

**Comment by kypvalanx** [comment]
this has been linked to the pinned mega issue for module support
