### ISSUE TITLE
[bug] [SWSE version 0.5.42] [Foundry 9.269] condition track use breaks tokens

### ISSUE THREAD

**Issue by marvinandroid01** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#280]
Whenever one of my players or I (the GM) use the condition track tools to move something up or down the condition track, nearly all character-specific data disappears from the token's character sheet.  I'm not savvy enough to know if the data is actually gone or not, but the only remedy is to delete the token and replace it with a new one (which brings the data back at the normal condition track setting).  Please see the comparison pictures below.

![image](https://user-images.githubusercontent.com/90999683/183280982-a31e4cd2-27ec-4b62-ad0b-3f6bf64c24d5.png)

![image](https://user-images.githubusercontent.com/90999683/183280956-c6e4a805-387c-4352-9d5e-fe46a54360b9.png)

Thank you for helping to remedy this!

**Comment by marvinandroid01** [comment]
I have not had that experience; see the picture above, where the condition track is back to full but the data is still gone.  The workaround I have had to do for bad guys is to open the main character data instead of the token data (I have them unlinked) and use that as a reference, manually correcting for condition track changes.

**Comment by LeKopic** [comment]
For the time being I would recommend downgrading your SWSE version one or two versions.

**Comment by kypvalanx** [comment]
technically a duplicate, so i'll close this one and link -> #273
