### ISSUE TITLE
[bug] [Foundry v. 9.269] [SWSE v. 0.5.42] damage doubling randomly

### ISSUE THREAD

**Issue by marvinandroid01** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#284]
When in combat, the system does not always double damage for natural 20s rolled, and sporadically doubles the damage for non-critical hits.  

This is an example from last night's game, when a player rolled a natural 20:
![image](https://user-images.githubusercontent.com/90999683/184547680-ab189c5b-0300-43a7-8ac3-fc5ed30879f2.png)
![image](https://user-images.githubusercontent.com/90999683/184546507-41473de8-b76f-4841-a18b-688abfaaf915.png)

And this is an example from one of my random mooks getting double damage when he shouldn't:
![image](https://user-images.githubusercontent.com/90999683/184546600-313325bd-bb16-4a6b-9d4d-5b6a8f16bc2d.png)
![image](https://user-images.githubusercontent.com/90999683/184546651-38bd2c95-6c46-44c7-a499-388f1ab299bc.png)
(mook's levels are nonheroic 3, Scout 3, so the half heroic level is calculating correctly and then being doubled with the dice damage).

The appearance of the d20 icon next to the attack roll reveals when the damage has been doubled, but it appears randomly rather than marking a critical hit (as I assume it is supposed to do).

Thank you for looking into this!  I'm sorry that I don't have the programming skills to assist further in debugging the issues, and I appreciate all the work done to get the game system as well-functioning as it is.

**Comment by kypvalanx** [comment]
this is a duplicate #272
