### ISSUE TITLE
[Bug] Starship skills do not include the bonuses provided by characters equipped to station slots.

### ISSUE THREAD

**Issue by Derinzed** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#286]

**Comment by kypvalanx** [comment]
i don't seem to be able to reproduce this, what kinds of bonuses aren't appearing?  it seems to work fine with skill bonuses from attributes and skill training.

**Comment by Derinzed** [comment]
I'll try again today, but a ship that has -8 to piloting with crew training of "-" continues to be -8 after placing a player with piloting 10 in the pilot seat.  Unless I misunderstand the rules of SWSE, it should become his piloting check instead.

**Comment by Derinzed** [comment]
![image](https://user-images.githubusercontent.com/45581121/185756436-2fab0aeb-2cc0-4207-a7f0-87f21964ac93.png)

Here you go.  the player is in the pilot seat of the vehicle, but the vehicle skill is still -8.  changing the crew quality still leaves it as -8.

**Comment by kypvalanx** [comment]
what does the breakdown say if you hover over the skill bonus on the ship sheet?

**Comment by Derinzed** [comment]
It says:
Attribute mod: 2
Ship size mod: -10

**Comment by kypvalanx** [comment]
interesting, can you send my the exported characters?

**Comment by Derinzed** [comment]
Sure. here you.

[Actors.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/9387747/Actors.zip)
