### ISSUE TITLE
Adding temporary stat bonus opens age dialogue

### ISSUE THREAD

**Issue by Ghoublai-Khan** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#29]

**Comment by kypvalanx** [comment]
wait... what?

**Comment by Rantarian** [comment]
This isn't quite correct. It is possible to add a temporary stat bonus, but if you hit the Enter key it will open the Age dialog.

**Comment by kypvalanx** [comment]
thank you for clarifying the problem... that's weird, i'll take a look.
