### ISSUE TITLE
Feat: Weapon Focus is missing weapon options in dropdown list

### ISSUE THREAD

**Issue by jasony1974** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#3]
The user is unable to select a weapon class from the dropdown list because there are no elements populating the list.

**Comment by jasony1974** [comment]
Lightsaber and Simple Weapons, which both come with the Jedi Class.  I
tried adding those two weapon proficiencies manually to see if that made a
difference but it did not seem to.

**Comment by kypvalanx** [comment]
i'll keep, looking it appears to work for me.  i'll keep looking to see if there's some kind of state being saved that you're not generating

![image](https://user-images.githubusercontent.com/7539264/115298285-e6ea3200-a122-11eb-8ed8-29d9b271dd32.png)

**Comment by jasony1974** [comment]
Hmm, my Feats table is not being populated, like yours is below. When I
drag the Jedi class to the character sheet, that tab stays blank, and even
if I drag those feats manually to the sheet, the feats tab stats blank.

**Comment by kypvalanx** [comment]
this should be fixed by 0.2.1
