### ISSUE TITLE
[Feature Request]/[Bug] Occupation Backgrounds

### ISSUE THREAD

**Issue by Tysdas** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#301]
Occupation backgrounds do not implement a +2 bonus on the occupations untrained skills.

**Comment by kypvalanx** [comment]
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/commit/2cd2a730941493fbd860b869dac6a277dd92974e
