### ISSUE TITLE
[Bug] Resource bars only update for token owner

### ISSUE THREAD

**Issue by Derinzed** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#304]
The token owner sees changes in resource bars, but will always show, for example, full health on all other tokens, regardless of their health.

As GM I can see: 
![image](https://user-images.githubusercontent.com/45581121/188202047-240a4c43-84ff-4f31-99b6-a1154b94d86e.png)

But the player (the token on the far left) only sees his bar as updated:
![image](https://user-images.githubusercontent.com/45581121/188202120-81698477-d7b1-4f22-9a29-b0afb981f480.png)

**Comment by kypvalanx** [comment]
are you sure that this isn't a visibility issue?  this might be tied to what permissions a given user has to the token

**Comment by Derinzed** [comment]
The bars are set to "Always for Everyone" you are correct that by giving players ownership of tokens it'll update for them too, but with the "Always for Everyone" setting it should also show to non-owned users. At least that's how it has worked in other systems.

**Comment by kypvalanx** [comment]
gotcha.  i'll take a look

**Comment by Derinzed** [comment]
Thanks. I appreciate it!

**Comment by kypvalanx** [comment]
i found the issue, since the user cannot update the sheet isn't being fully generated, ie, health isn't being generated correctly.  ironically, it's due to this change https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/commit/1a2d27604882036d652ade42fbe6ff4263b7b1c1

i'll have to find a different way to solve that problem.

**Comment by kypvalanx** [comment]
i reused your solution to wrap update calls to prevent sheets from trying to update on clients without permissions.
