### ISSUE TITLE
[Bug] Beastmaster Talent Tree

### ISSUE THREAD

**Issue by Tysdas** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#308]
The beast master talent tree is qualified by Dathomiri Witches equivalent talents.
IF you have the Dathomiri witch version of the talent you currently do not meet the pre. reqs.

**Comment by kypvalanx** [comment]
do you know if this applies to felucian shaman talents as well?  do they have to have text explicitly stating that identical talents count as each other?
