### ISSUE TITLE
Cannot add force talents to Force Prodigy class

### ISSUE THREAD

**Issue by Nattnissen** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#314]
When I try adding any force talent to the Force Prodigy class I get a message saying you don't have any more talents available of these types *

**Comment by kypvalanx** [comment]
can you screen shot the character sheet?

**Comment by kypvalanx** [comment]
also, what are you trying to add?

**Comment by Nattnissen** [comment]
Trying to add telekinetic prodigy, but it seems like it won't allow me to add any  force talent at all.

Right now the character is multi-classed with 1 level prodigy and 1 level jedi

![image](https://user-images.githubusercontent.com/54192490/193326633-0d41b89d-27df-4631-bd2a-08d284363193.png)

**Comment by Nattnissen** [comment]
After posting the bug I noticed that we are using version 0.5.1, so could be the problem is gone in later versions.

**Comment by kypvalanx** [comment]
i did fix a similiar problem since then, so let me know.  keep in mind that updating to latest requires a V10 uplift

**Comment by Nattnissen** [comment]
On v10 now and using the latest update, but still unable to add any force talent when using the Force Prodigy class.

**Comment by kypvalanx** [comment]
ok, i'll take a look
