### ISSUE TITLE
[Bug] Too many skills 

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#316]
As far as I can tell, every new level adds skills to train. For example, a new droid character with soldier 1:
![image](https://user-images.githubusercontent.com/42682507/193398950-51034f9e-a6f1-4e65-9292-80613d8de9a0.png)

The same droid with soldier 3:
![image](https://user-images.githubusercontent.com/42682507/193398975-b44def1a-5a0a-40cc-98fa-e4fb6b5ae1f2.png)

**Comment by kypvalanx** [comment]
with some of the rework i did last week, the item is now being passed consistently throughout the attribute resolution method.  specifically for the item filter that was being used, it expected the items data model and so was getting an undefined item.
