### ISSUE TITLE
Multiclassing Jedi and Lightsaber feat

### ISSUE THREAD

**Issue by Nattnissen** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#326]
When trying to select Lightsaber proficiency as the multiclass feat it won't allow it.

It worked fine in and older V9 version, so something must have been altered since then

![image](https://user-images.githubusercontent.com/54192490/194896385-327769fa-d345-4ded-9321-53d5040ff07f.png)

**Comment by kypvalanx** [comment]
should be fixed by this i think https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/commit/c83d1adfd0248bc8155856de026b76509276d66c

**Comment by kypvalanx** [comment]
i should have tested before commenting.  i have now tested, it does work.
