### ISSUE TITLE
Defense change suggestions

### ISSUE THREAD

**Issue by EmeraldTails** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#329]
Hello, I was wondering if I could make a suggestion regarding the defenses. Would it be possible to include a drop-down attached to the stat modifiers, or have the feats hard-code it? For Predictive Defense, it would be either Reflex or intelligence, Resilient Strength for Fort's Constitution, Or Strength. And with Indomitable Personality for Will defense, either Wisdom or Charisma.

**Comment by kypvalanx** [comment]
i can add that for predictive defense.  you can do it yourself while you wait. add an attribute to the feat with a key of reflexDefenseBonus and a value of ```MAX(@DEXMOD, @INTMOD) - @DEXMOD```

resilient strength would be the same kind of thing but with a key of fortDefenseBonus and a value of ```MAX(@STRMOD, @CONMOD) - @CONMOD```

indomitable personality appears to be a situational bonus and idr how to add that off the top of my head, it might just be to add a special modifier field.

**Comment by EmeraldTails** [comment]
My mistake, I was searching through the feats and came across the first thing that looked like something related to the other two feats. The actual feat that applies permanently is Force of Personality, apologies.

**Comment by kypvalanx** [comment]
willDefenseBonus ```MAX(@WISMOD, @CHAMOD) - @WISMOD```

identical to the zygerian trait.  force of personality should just not work for zygerians, but that will actually cause a bug

**Comment by kypvalanx** [comment]
fixed in 9b6977831d2927ce67cc19c8b2b6c64b963dc122
