### ISSUE TITLE
Be able to add sound to weapon attack

### ISSUE THREAD

**Issue by Vaslayak** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#331]
The module Maestro is already capable to do such thing so maybe a look in this could be helpful.

Video attach of the module setup:https://youtu.be/5C4BnpO9HIE?t=209

Module link: https://foundryvtt.com/packages/maestro

**Comment by kypvalanx** [comment]
fixed in 9b6977831d2927ce67cc19c8b2b6c64b963dc122
