### ISSUE TITLE
Telekinetic Prodigy Talent doesn't give extra force power

### ISSUE THREAD

**Issue by Vaslayak** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#333]
As the title said, if you take the talent and then take the Force training Feat. If you take the move object power you should be able to get a other force power for free. For now it's not the case, you don't get any other force power.
![Capture d’écran 2022-09-04 110826](https://user-images.githubusercontent.com/109117919/197078800-1ba56292-1892-40ca-aa68-c3fc482285d8.png)

**Comment by kypvalanx** [comment]
i'll get to this soon.  i just wanted to thank you for filling out this issue so well.  the screen shot and description are excellent.

**Comment by kypvalanx** [comment]
fixed in 9b6977831d2927ce67cc19c8b2b6c64b963dc122
