### ISSUE TITLE
[Bug] Type and Subtype

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#335]
As seen in the image below, I have some problems with type and subtypes when I open items, talents or feats.
![image](https://user-images.githubusercontent.com/42682507/198897003-643b31bb-18e6-4993-9c93-a398c8a017ad.png)
When I close an opened items/talent/feat I see these errors:

![image](https://user-images.githubusercontent.com/42682507/198897042-41852afa-4274-43ef-932e-ddcfa58a1fca.png)
![image](https://user-images.githubusercontent.com/42682507/198897047-4c1e83cc-462b-4eaa-b31f-2f67f25b7a1c.png)

**Comment by kypvalanx** [comment]
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/0.6.15

this should be resolved as of 0.6.15
