### ISSUE TITLE
[Bug][1.6.14] Actor Compendium - Units CL 0-2 - Stats are all at 10

### ISSUE THREAD

**Issue by Orkah** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#340]
Tested on Foundry VTT v10 Build 283 & 290 with version 1.6.14 (Fresh Installation via system.json link, with no mods)

The actor listed in the compendium have all there stats to 10 when clicking on them, or importing them.
The stats values are still inside the packs database files, this is why I think it might be a bug.

![SagaEditionFoundryVTT](https://user-images.githubusercontent.com/10533768/203874235-c95844ec-4833-49d0-933e-446406145260.png)

**Comment by Orkah** [comment]
It is probably unrelated;

When clicking on "Return to Setup" inside the game world.
There is a compatibility warning from Foundry.

```
[swse] The system "swse" is using "name" which is deprecated in favor of "id"
#logPackageWarnings @ setup.js:145
_setupView @ setup.js:124
_initializeView @ setup.js:73
initialize @ foundry.js:7782
await in initialize (async)
window.addEventListener.once @ foundry.js:79319
```

![SagaEditionFoundryVTT_2](https://user-images.githubusercontent.com/10533768/203874412-aea3ffb9-cb3f-4906-a2ca-943431238208.png)

**Comment by kypvalanx** [comment]
this issue is a symptom that tends to indicate an underlying issue that prevents the sheet from finishing generation.  I'll close this, and future examples of this issue should be reported on new issues.  I'll also work on making it stop being an indicator.
