### ISSUE TITLE
Equipping weapons creates empty (non-usable) attacks

### ISSUE THREAD

**Issue by LoZeno** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#342]
Foundry version: 10, build 291
Star Wars: Saga Edition version: 0.6.15

After creating a completely new campaign and a completely new character, at level 1, I added a weapon (lightsaber) and equipped it, but on the Summary tab it creates an empty attack with no usable option during combat:
![image](https://user-images.githubusercontent.com/3267561/210759150-4d3b51c6-17b8-428b-8ac6-d71a4afb5171.png)

**Comment by LeKopic** [comment]
Hit F5 and wait for Foundry to reload, then the issue should be resolved (for that char sheet at least).

**Comment by LoZeno** [comment]
Yup, that works.
I created a new character right after and I still had to hit F5 to fix that new character's attacks... slightly annoying, but we can live with the workaround.
Thank you!
