### ISSUE TITLE
[Bug] [0.6.17] Damage is broken

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#346]
Another bug in 0.6.17 - no damage dice. Tested with several weapons and several different characters.
![image](https://user-images.githubusercontent.com/42682507/211171719-31b243e6-9f60-45f4-8dd7-5fbb55fa4212.png)

**Comment by kypvalanx** [comment]
i used a for in loop instead of a for of loop when using multiple attribute keys.  this will be fixed in the next update
