### ISSUE TITLE
Improved damage threshold feat can't be selected more than once

### ISSUE THREAD

**Issue by Nattnissen** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#349]
![image](https://user-images.githubusercontent.com/54192490/211218999-9831b18b-fb22-439f-a797-d48d80e21edf.png)
![image](https://user-images.githubusercontent.com/54192490/211219021-4f93a7aa-5b8d-4c19-8d72-511c24cc98b2.png)

It's not possible to select this feat more than once

**Comment by Nattnissen** [comment]
Forget it. I'm dumb XD
It's a general feat only not a bonus feat for soldier

**Comment by kypvalanx** [comment]
no worries, i'm glad you submitted what you thought was a bug.  please continue as you find them
