### ISSUE TITLE
[Suggestion] Damage Modifier

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#351]
Suggestion: Add an ability to write additional dice into Damage Modifier when rolling an attack, if possible.
![image](https://user-images.githubusercontent.com/42682507/212560692-5a354140-74d4-45d6-9ca9-a02f8fb411e6.png)

**Comment by marvinandroid01** [comment]
My party would also love to see this feature added; we do a lot with Rapid Shot, Deadeye, and Mighty Swing, so this comes up every fight.
