### ISSUE TITLE
[Bug] Dual Weapon Mastery

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#352]
Dual Weapon Mastery feats don't work when committing a full attack.
![image](https://user-images.githubusercontent.com/42682507/212562365-e84809f1-49f6-4167-9607-07e29111badb.png)

**Comment by Vaslayak** [comment]
Can confirm, I try with differents weapons, Electrostaff and double blade lightsaber and got the same result

**Comment by kypvalanx** [comment]
looks like the old version of caching that this method uses is screwing it up. i'll give it a look
