### ISSUE TITLE
[Suggestion] A button to print defenses to the chat

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#354]
Click button -> send a chat message with defenses, possibly as a small table.
![image](https://user-images.githubusercontent.com/42682507/215478683-6006dd3e-7f1a-45c0-ae66-22b5f75d356e.png)

**Comment by kypvalanx** [comment]
fixed in 9b6977831d2927ce67cc19c8b2b6c64b963dc122
