### ISSUE TITLE
(Enhancement) Override the HP total box

### ISSUE THREAD

**Issue by Vaslayak** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#363]
I was trying to recreate the B3-Series Ultra Battle Droid and it's a Non heroic 9 and should get 42 hit point. Non heroic are cap to 4 hp per level so at level 9 it's maximum hp is 36. Maybe I'm missing something here but yeah the Hp override would be cool for thoses situation.
![Capture d’écran 2023-02-24 174903](https://user-images.githubusercontent.com/109117919/221380779-3484ee3c-4c43-4b31-b0d6-5da1165162b6.jpg)

**Comment by kypvalanx** [comment]
I made a prototype where you could right click on HP to override, idk if I released that.

**Comment by kypvalanx** [comment]
i did release it, you can right click HP to override
