### ISSUE TITLE
(Enhancement) Allow manual rolls to be input in "roll" attribute generation type

### ISSUE THREAD

**Issue by P0Pss** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#365]
Switching to foundryVTT from would be nice to be able to keep old rolls, as well as keep the automation of changes such as race bonuses. Basically selecting "Roll" for attribute generation type, then being able to override the rolled dice.

**Comment by kypvalanx** [comment]
a new mode for "manual rolling" where values of dice rolls can be put in, but unlike Manual mode automatic values are applied from species etc.
