### ISSUE TITLE
Attack buttons go missing after viewing items

### ISSUE THREAD

**Issue by knive79** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#372]
The error occurs after viewing a weapon on a character or vehicle in the systems tab

After viewing the weapon the associated attack mode disappears in the summary tab, even if the item appears unchanged

![image](https://user-images.githubusercontent.com/127705251/224590951-cc076396-e8ec-48df-8fbe-8f31385029d3.png)
![image](https://user-images.githubusercontent.com/127705251/224591210-19c7b5d8-294b-4a3c-a97a-60a718e60daf.png)
![image](https://user-images.githubusercontent.com/127705251/224591246-cdd35bda-cad7-413c-af5f-a12fbecfc7dc.png)
![image](https://user-images.githubusercontent.com/127705251/224591282-2c5a9977-dd2a-40a6-b547-d4ffb0a55ea3.png)

**Comment by kypvalanx** [comment]
something in the item sheet is throwing an error preventing the attack section from being drawn.  try again, but hit F12 and see what errors pop up

**Comment by kypvalanx** [comment]
this has been fixed by recent overhaul
