### ISSUE TITLE
[Bug] NaN equipment weight

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#374]
If there is a datapad in the inventory then the weight is listed as NaN:
![image](https://user-images.githubusercontent.com/42682507/228967038-e7cf4c48-7975-4398-9cc6-d29b1a5dfa3a.png)

If there is no datapad:
![image](https://user-images.githubusercontent.com/42682507/228967110-6feac5a1-6747-4314-8c2e-1dfdb49db00a.png)

I think it is either because there are two weight options or because it doesn't have a weight listed in the system?

**Comment by kypvalanx** [comment]
yeah, it's because it can't parse the string "see below"  i'll probably have to make manual items for that.
