### ISSUE TITLE
[Bug] Incorrect Attack Result

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#378]
I suspect attack result is based on the die, not on the result.
![image](https://user-images.githubusercontent.com/42682507/229288312-10f21d29-558c-4041-ac6e-5e14285fe812.png)

**Comment by kypvalanx** [comment]
fixed here 03aabc1e096d006b1c5762ccc1eca04c3da46a09
