### ISSUE TITLE
[Enhancement] Add a note/option to skill checks when a reroll is allowed

### ISSUE THREAD

**Issue by TalonKetupa** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#385]
Many talents or feats give a character the option to reroll a skill and take the second result. It would be beneficial to have a visual indicator to the player to cue them when this is available to them.

Currently: The only way to know if a character has a reroll available to them is to search through the talent/feat descriptions. This is cumbersome.

Suggested Enhancement option 1: add text to either the output in chat or underneath the skill itself on the summary page that notes whether a character may opt to reroll.

Suggested Enhancement option 2: when a skill is rolled which has an allowed reroll, open a confirmation window asking player if they would like to reroll (and resolve it).

**Comment by kypvalanx** [comment]
this is available on most talents and feats and traits that provide this.  i don't guarantee that i found them all.  the prompt will appear on the chat card for the roll
