### ISSUE TITLE
Currently conflicting with Dice so Nice Module

### ISSUE THREAD

**Issue by jkallan** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#386]
Hi! Currently Dice so Nice does not play well with this module when it comes to editing attacks. When a die is added to the damage bar, nothing will happen and this error comes up in the console log. 
<img width="554" alt="Screenshot 2023-04-04 at 2 00 10 PM" src="https://user-images.githubusercontent.com/129892898/229883839-e1f4984a-0a06-4921-b3bd-0d15c61e1933.png">

thanks for your help and your great work!

-Joseph

**Comment by TalonKetupa** [comment]
Tested swse version 0.7.11
with Dice so Nice version 4.6.8

Looks to be working fine.
