### ISSUE TITLE
Cant add edit weapon attributes in custom weapon modes

### ISSUE THREAD

**Issue by jkallan** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#387]
right now you cant create a new mode for an item (weapon) and add an attribute. You can add attributes to the standard mode, and you can create new modes on the item, but you cant create special attirubte for a new mode. 
<img width="422" alt="Screenshot 2023-04-04 at 2 32 26 PM" src="https://user-images.githubusercontent.com/129892898/229885834-72a3a97d-a5d0-409a-86f9-67b264183d38.png">

Thanks!

**Comment by kypvalanx** [comment]
this system is being replaced in the 0.7.0 release.  i'm not fixing the existing system.
