### ISSUE TITLE
[BUG] Imperial Knight prestige class special prerequisite can't be fulfilled. 

### ISSUE THREAD

**Issue by Lukeirish8** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#388]
Imperial Knight Prestige class has a special prerequisite that requires "Must be a sworn defender of Emperor Roan Fel."
Adding Affliations with "The Imperial Knights" and/or "The Fel Empire" does not fulfill this requirement.
![image](https://user-images.githubusercontent.com/131107369/232652985-d5686f42-d0af-4533-a0ae-8452adb7ac66.png)

![image](https://user-images.githubusercontent.com/131107369/232653690-1410cf55-9bcd-4db1-9d01-9c40a826e1f7.png)

**Comment by kypvalanx** [comment]
this was fixed when I made SPECIAL prerequisites optional
