### ISSUE TITLE
TypeError:  Cannot read properties of undefined (reading 'getCached')

### ISSUE THREAD

**Issue by DieKartoffelGranate** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#408]
I wanted to bring your attention to this since I didn't immediately see something bringing it up in the other issues, but I happened to notice this error in the console.  I don't know if it is actually causing any problems, but some compendiums seem to be slow to open and I wonder if it may be a contributing factor.

![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/81174533/5c832fba-70dc-45f9-a200-5487acfae990)

**Comment by kypvalanx** [comment]
make sure you're up to date.  that stack trace has some methods that have not existed for many versions.  i'll close this for now, reopen if you can confirm that you are up to date and the problem persists.
