### ISSUE TITLE
Can't apply "Double" template on a vehicle weapon

### ISSUE THREAD

**Issue by xenogray** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#409]
Foundry version : 11.307
SagaEdition : 0.7.5

<img width="500" alt="2023-08-22 20_35_26-Foundry Virtual Tabletop" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/127744116/308c6e50-385a-4748-a1c6-5dd8efba27a3">

Trying to add the "Double" template over a vehicle cannon and it says that.

[fvtt-Actor-new-actor-(6)-s0EpZwRbGMlBmznZ.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/12411781/fvtt-Actor-new-actor-.6.-s0EpZwRbGMlBmznZ.zip)

Hope that will be enough to help :)

Thank you !

**Comment by kypvalanx** [comment]
you need to drag "Double" to the weapons item page.  i will add an enhancement to allow it to work the way you were attempting to do it.
