### ISSUE TITLE
0.7.7 cannot add class to actor

### ISSUE THREAD

**Issue by TalonKetupa** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#411]
Steps to reproduce:

1. start game.
2. create new actor (character).
3. add species.
4. add class (I used soldier).
5. Class is not visually added to the actor sheet and errors on console.

Console log and a picture attached.

[SWSE_0.7.7_console_errors.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/12643648/SWSE_0.7.7_console_errors.zip)

**Comment by kypvalanx** [comment]
this should work in 0.7.8
