### ISSUE TITLE
[Bug] Heroic level is not shown under Defenses on Character Sheet

### ISSUE THREAD

**Issue by cpadilla** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#415]
![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/b229ca9a-89dc-4e44-a9e6-1ad619828825)

I have two heroic classes leveled on this character and yet I am not seeing my heroic level shown under Level/Armor bonus.

Based on the [wiki](https://swse.fandom.com/wiki/Defenses), the defenses should be calculated as such:

> Reflex Defense: 10 + Heroic Level or Armor Bonus + [Dexterity](https://swse.fandom.com/wiki/Dexterity) Modifier + [Class](https://swse.fandom.com/wiki/Class) Bonus + Size Modifier
Fortitude Defense: 10 + Heroic Level + [Constitution](https://swse.fandom.com/wiki/Constitution) Modifier + [Class](https://swse.fandom.com/wiki/Class) Bonus + [Equipment](https://swse.fandom.com/wiki/Equipment) Bonus
Will Defense: 10 + Heroic Level + [Wisdom](https://swse.fandom.com/wiki/Wisdom) Modifier + [Class](https://swse.fandom.com/wiki/Class) Bonus

I would expect the Reflex Defense to take the greater of the two values, but Fortitude and Will Defense should both include Heroic Level as well.

**Comment by vertigoogle** [comment]
Fixed with https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/0.7.11
Testing OK
