### ISSUE TITLE
Blaster Carbine in Compendium has incorrect stats

### ISSUE THREAD

**Issue by cpadilla** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#416]
There appears to be a few things wrong with the stats on the Blaster Carbine as is found in the Weapons Compendium.

First of all, there is a static -5 toHitModifier attribute on the weapon of which I could not find a good explanation for. There is another -5 modifier when Autofire is toggled, which is as expected. However, I found when equipping a character with this gun straight from the Compendium, I was seeing a third -5 modifier, which I could only assume was from my character wearing armor (however this should only have been a -2 modifier since I was wearing light armor, but actually should have been 0 since my character was proficient in that armor type). I think unequipping and reequipping the armor removed the third -5 modifier, but I think it's probably bugged.

Secondly, the stun damage on the Blaster Carbine should be 2d8 instead of 3d8.

I was able to work around this by creating a custom item with similar stats but removing the toHitModifier and changing the stun damage so this should be a simple fix for the stats I can probably open a PR for soon. However, some investigation should be done to reproduce the other mysterious -5 modifer I was seeing.

![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/ba99653a-5baa-4ee0-ac89-646abe3849d1)

**Comment by cpadilla** [comment]
Apparently the book was errata-ed so that the stun damage now is the same as the normal damage so we can disregard that portion of the issue.

That just leaves the -5 modifiers which are NOT related to Autofire. As shown in the screenshot, there are three -5 modifiers on the attack, one of which is from the Autofire mode, the other two which appear to be bugged.

**Comment by cpadilla** [comment]
I definitely think this is a bug with the toHitModifier attribute. Deleting the Blaster Carbine from my inventory removes the -5 modifier on my unarmed attacks. I also tested it by creating a custom Blaster Carbine which you can see below. The one on the left is the Blaster Carbine from the Compendium, the one on the right is the one I created, setting the toHitModifier to 0 by default. The custom one I made behaves as you would expect it to.

![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/2ec9fee0-9f7a-4da1-b64f-21b397bdb169)

**Comment by cpadilla** [comment]
This seems to be a common issue with any weapon that has an Autofire feature.

**Comment by kypvalanx** [comment]
5cf1a1a9c6b9ee1a99a6465862311036f192f888 fixes this
