### ISSUE TITLE
Encumbrance meter is broken

### ISSUE THREAD

**Issue by cpadilla** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#417]
I added a character with multiple items in inventory with the weight attribute, but the encumbrance meter still shows as 0.

![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/6bc55d22-e72d-4d77-bb27-7c3f06fda7a1)

**Comment by TalonKetupa** [comment]
Real quick, can you check and see your settings for encumbrance?

<img width="839" alt="image" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/86027445/076b3bd0-8fa5-4e66-b328-546e4bb617d2">

**Comment by cpadilla** [comment]
Yes, it is enabled.
