### ISSUE TITLE
Interactions with Equipment revert Actor Form to new form

### ISSUE THREAD

**Issue by Rantarian** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#42]
Hard to describe what happened here but it only seems to occur with items in the Unequipped/Equipped sections.
Moving items between these sections appears to revert the form to that of a new character, but doesn't mess up the character itself.

**Comment by kypvalanx** [comment]
should be fixed in [0.4.2](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/0.4.2)
