### ISSUE TITLE
Changing an item's name disrupts the upgrade point calculations

### ISSUE THREAD

**Issue by TalonKetupa** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#420]
Steps to duplicate:
1. add Disruptor Pistol to Actor.
2. on Disruptor Pistol->Stripping, select Reduce Range.
3. on Disruptor Pistol->Modifications, add Beam Splitter.
4. Upgrade Points calculate appropriately. Image attached.
<img width="410" alt="image" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/86027445/bb23cf42-93f8-4a65-807a-2ac70b3e687e">

5. Change Disruptor Pistol name to "My cool blaster".
6. Upgrade Points no longer calculate appropriately. Image attached.
<img width="456" alt="image" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/86027445/0ad8cb5b-f021-434b-a69e-1f8e13a3998c">

**Comment by kypvalanx** [comment]
when reproducing, upgrade points were never correct for me
