### ISSUE TITLE
Provide movement speed and it's type for selected token

### ISSUE THREAD

**Issue by vertigoogle** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#423]
When selecting a token, the maximum movement speed the token has should be provided in the actor data
1. value as int
2. type as string (flying, basic)

TYVM!

Followup from https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/pull/418

**Comment by kypvalanx** [comment]
is there a specific place that it should be provided?  is this for that module?

**Comment by kypvalanx** [comment]
this is now provided by actor.gridSpeeds  .  this will give you an array of objects with value and type of movement.  I'd love to play with all of the droid movement types but i don't think that's super important right now.  maybe when i work on terrain
