### ISSUE TITLE
Droid species receives CON ability bonus to Fortitude defense

### ISSUE THREAD

**Issue by cpadilla** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#425]
Droid species appear to still have their Constitution abililty bonus calculated into their Fortitude defense. According to the wiki, Fortitude Defense should be calculated as:
> 10 + Heroic Level + [Constitution](https://swse.fandom.com/wiki/Constitution) Modifier + [Class](https://swse.fandom.com/wiki/Class) Bonus + [Equipment](https://swse.fandom.com/wiki/Equipment) Bonus

Since Droids don't get Constitutions, there should be no ability modifier added.

![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/ea368f52-7546-4520-aa0c-b6b40fe06d62)

**Comment by TalonKetupa** [comment]
Actually, droids and other nonliving targets without a constitution score add Strength modifier to Fortitude Defense.

See **https://swse.fandom.com/wiki/Defenses**
