### ISSUE TITLE
[Compendium] Pirate (DMF) CL3 not importing correctly

### ISSUE THREAD

**Issue by cpadilla** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#429]
The stats don't seem to get imported correctly for Pirate (DMF) CL3.
![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/547b1da5-0ec2-4a20-ad98-f7ef3c9faef5)

**Comment by cpadilla** [comment]
After spending a bit more time looking at the character sheet, I think there is nothing wrong here actually, I think I was just expecting there to be no validation issues when creating npcs from the Compendium.

If there is a bug, perhaps it is that the Current Hit Points exceeds the Total Hit Points. Perhaps validation can be added for that as well?

**Comment by kypvalanx** [comment]
this has been fixed as part of another update
