### ISSUE TITLE
Issues when creating an actor using the Yuuzhan Vong Advanced Agent

### ISSUE THREAD

**Issue by cpadilla** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#431]
When dragging a Yuuzhan Vong Advanced Agent from the Compendium into your list of actors, there immediately is a number of error messages reading the same error:
![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/ca113ed0-6341-47b9-aed7-086ec01630aa)

Opening up the character sheet for the npc, there are a number of validation errors that come up.
![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/3e0d48ac-7658-4741-82a1-0ea69b86431a)

Despite all the validation errors, I believe the main issue is that there are skills to be trained but the checkboxes to train skills is missing from the list of skills so you can't select skills to train. This prevents Skill Focus (Deception) and Skill Focus (Stealth) from being added.

![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/2ea70b8f-42e2-4b37-869e-1c7b52606c30)

**Comment by kypvalanx** [comment]
no longer occurs in latest 0.7.21
