### ISSUE TITLE
Create a CONTRIBUTING.MD

### ISSUE THREAD

**Issue by cpadilla** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#432]
I think this repository could benefit from having an official contributing document to help new developers onboard to the project.

From what I understand after watching @kypvalanx 's last stream, there are a few things essentially hard coded to his machine.

I think the CONTRIBUTING.MD document should identify all the places where hardcoded references need to be updated locally. Or, as part of the work for this issue, those references should be updated to be relative.

Any other build steps should be documented as well, such as building the Compendium.

**Comment by kypvalanx** [comment]
added
