### ISSUE TITLE
Add trackable ammunition for weapon instances

### ISSUE THREAD

**Issue by vertigoogle** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#436]
My players have a hard time to track their shots left in their blasters, bowcasters and so on.

So I thought it would be nice to be able to let the system do the work for them, like I saw in this roll20-featured player group:
![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/47757714/1f6feced-6e24-4220-8aab-9eafe91b1196)

The implementation of this could have 2 steps:
1. Enable a field on the weapon instance in the inventory for max ammon and current ammo
1a. Bonus: Implement a button to reload a weapon by using a energy cell or power pack in the inventory
1b. Bonus: Implement a button at energy cells, power packs to mark (or unmark) them as used/empty

2. Automatically draw shots from the weapon, when an attack is rolled
2a. Bonus: Calculate the drawn shots by attack mode (Autofire, Single Shot, Stun...)
2b. Bonus: Prevent attack roll (or show a notification in chat instead) when an unloaded weapon is used, meaning not enough shots are left in the energy providing item

Let me know what you think about this feature!

**Comment by kypvalanx** [comment]
ammo tracking should occur when a change is added to a weapon with the "ammo" key

**Comment by kypvalanx** [comment]
reopening to host feedback

**Comment by kypvalanx** [comment]
next step will be to add more feedback and lock this feature behind a configuration option.

i think that the attack message should include some information.  feedback when there is not enough ammo or new ammo packs makes sense to me also.
