### ISSUE TITLE
NaN damage on Double Weapons

### ISSUE THREAD

**Issue by cpadilla** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#437]
When equipping a Double Weapon, such as the Shockstaff, the attack shows NaN as the damage amount. This is most likely due to the damage on the weapon on the wiki being listed as `2d6/2d6`. The damage should be parsed as the first half before the `/` since it looks like most Double Weapons have identical damage on both sides.

Perhaps adding a new mode for Double Weapons is necessary to calculate if the attack is using both ends of the weapon as a Full-Round Action. A -10 penalty should be applied by default, with certain Feats and Talents that can reduce these penalties.

![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/b9f089a5-164a-4532-9e09-506cf3075cbc)

**Comment by kypvalanx** [comment]
this is fixed, but there is a little more work i'd like to do before closing
