### ISSUE TITLE
Talents: Cannot add any talents 

### ISSUE THREAD

**Issue by 4lbburrito** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#44]
I've attempted to make a new multiple different character sheets and with each one, I can't add any talents. When I try to drop a talent in I get "You can't take any more talents of that type", I get this when trying to build out a high level character or a single character with just one level. No matter the class or level, I always get the same message. 

I've also tried this with the game paused and unpaused.

**Comment by rainbowlarva** [comment]
Also having this issue. I've tried creating my own custom talents to drop in and it still doesn't let me add any. I went ahead and tried to edit it myself to see if I could fix it, but no matter what I did it still spit out the same result.

**Comment by rainbowlarva** [comment]
This is all that shows up in the console when trying to add talents.
![Capture](https://user-images.githubusercontent.com/86572604/123557547-488fd380-d746-11eb-9c64-e2f551b2d884.PNG)

**Comment by kypvalanx** [comment]
This should work in latest
