### ISSUE TITLE
Setting to change how criticals are calculated in the system

### ISSUE THREAD

**Issue by TheAntiFunEquation** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#449]
What it says on the tin. Not high priority, but would be nice to change between default double damage, crunchy crits, double dice, etc!
Thanks!

**Comment by vertigoogle** [comment]
Unfortunately I am not into the calculations behind these methods you mentioned, @TheAntiFunEquation
Can you explain please what you mean by "crunchy crits", "double dice" and "etc."?
Thanks

**Comment by TalonKetupa** [comment]
**default swse** is Multiply total damage by 2. 
- 3d6+5, crit (3d6+5) x2

**double dice** refers to the dnd way where you roll the dice part of the damage twice. 
- 3d6+5, crit 6d6+5

**crunchy crit** usually refers to roll damage normally than add the max damage on top of that
- 3d6+5, crit 3d6+5+23

there is also just crit does **max damage**
- 3d6+5, crit = 23
