### ISSUE TITLE
New Homebrew Rule Request

### ISSUE THREAD

**Issue by jkallan** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#460]
There are two pretty popular house rules that are currently not supported by the module. Both of these feats are also accomplished by a feat and a talent respectively. While you can manually add these as GM feats/talents, it would be much simpler to have them an optional house rule adding these abilities to the character sheets automatically. This would save a lot of time in West Marches style games specifically.

Feat - Unleashed: Generally, games that use unleashed powers are games where everyone is expected to get unleashed abilities. DMs will then give everyone the unleashed feat to give them abilities. 

Talent - Armored Defense: Armor is really not worth it after the first three levels. A common house rule to mitigate this is to let everyone take the higheset of the two given options. However, this is also the effect of the first Armor Specialist Talent. Giving this specific talent to everyone would allow this house rule to work and it would allow people who wish progress in the Armor Specialist talent tree to do so without having to waste a talent on something that everyone already has.

Thanks!

**Comment by kypvalanx** [comment]
i think i might add this as a rule section in settings.
always adds
conditionally adds

**Comment by kypvalanx** [comment]
new settings added. let me know if i can make the instructions more clear
