### ISSUE TITLE
Health Defaulting to ten on Token HUD

### ISSUE THREAD

**Issue by jkallan** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#467]
Currently tokens can subtract PC health correctly, but you cannot add health to the character in this method. The health bar also will not diminish on the token until the token has less than ten health, so somewhere the tokens are defaulting to ten.

HEre are some pictures of the issue.

<img width="301" alt="Screenshot 2024-04-22 at 10 28 19 AM" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/129892898/39ea336b-25f6-44c1-9f4a-5a763c72a84d">
<img width="359" alt="Screenshot 2024-04-22 at 10 28 25 AM" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/129892898/d2aae41c-9f6c-4005-b879-2b23a0a6e9d8">
<img width="351" alt="Screenshot 2024-04-22 at 10 28 30 AM" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/129892898/89970b78-7d6d-44a7-abbe-4f84490245d5">
<img width="395" alt="Screenshot 2024-04-22 at 10 28 40 AM" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/129892898/d87469b1-0f05-4f05-90de-3f79ed919b87">
<img width="335" alt="Screenshot 2024-04-22 at 10 28 45 AM" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/129892898/a56c7bb7-20a4-4bd8-832e-3028550561de">
<img width="358" alt="Screenshot 2024-04-22 at 10 30 13 AM" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/129892898/1de1db70-b528-48b3-8ab3-d84ec770f441">
<img width="365" alt="Screenshot 2024-04-22 at 10 30 18 AM" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/129892898/7b0d4bb6-d97b-4a21-85b5-e0107561479c">
<img width="349" alt="Screenshot 2024-04-22 at 10 30 23 AM" src="https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/129892898/d4e8995d-e8cc-4201-beb0-a57121641746">

Edit: I was wrong, you cant subract health from PCs healht correctly either rn.

**Comment by TalonKetupa** [comment]
Can you attach the export for the player character you are seeing this issue on? (Right-click the listed character from the actors tab and select export)

**Comment by jkallan** [comment]
Hi! Here it is, though i will say it works like this on every single player token.

[fvtt-Actor-harg-borgor-Ntu2N0kuz62siJ7c.json](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/15083940/fvtt-Actor-harg-borgor-Ntu2N0kuz62siJ7c.json)

**Comment by TalonKetupa** [comment]
Oh OK. That's good to know also.
