### ISSUE TITLE
[Homebrew/Houserule] Option to combine Climb Jump and Swim as athletics

### ISSUE THREAD

**Issue by jkallan** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#476]
A common house rule is combing the athetic feats (climb, jump, and swim) into the "athletics skill" - IO can see this working like a checkbox that turns this setting on or off, or it could the feat coupling you already have set up where if you take jump you automatically get swim and climb.

**Comment by jkallan** [comment]
Alternatively, it might make more sense to put jump with Acorbatics as per Dart Author's houserules.
https://swse.fandom.com/wiki/Darthauthor%27s_House_Rules

**Comment by jkallan** [comment]
Actually, after a week of thinking, i think the best move would be to do something similar to how you have feats talents set up so that taking one skill can automatically grant you another skill. That way, you can implement all of Lil Literalists house rules at your own leisure without making a dedicated setting on foundry for it.

**Comment by kypvalanx** [comment]
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/releases/tag/12.0.1
