### ISSUE TITLE
[bug] Allow talents to be taken multiple times

### ISSUE THREAD

**Issue by jkallan** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#478]
Currently, you can't drag sentinel strike onto your sheet more than once but its a talent that you can take multiple times 

https://swse.fandom.com/wiki/Jedi_Sentinel_Talent_Tree#Sentinel_Strike

**Comment by kypvalanx** [comment]
fixed here 1a694808a6873032af00130fc42652f6e8530d14
