### ISSUE TITLE
Defensive Circle

### ISSUE THREAD

**Issue by DiamonDKZ** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#483]
![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/175145529/02d9e51d-fb3e-4468-8938-31ea11c18c43)
That talent (Defensive Circle) don't count as a Jedi Knight Talent

**Comment by kypvalanx** [comment]
yes it does, that's stating that you're required to have another jedi battle commander talent on your sheet.  I just verified that i can add it after adding jedi battle commander and block
