### ISSUE TITLE
[BUG] Initiative Not Working in Encounter Tab

### ISSUE THREAD

**Issue by TechpriestFL** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#484]
Encounter Tracker and Combat Carousel (mod) are not adding Initiative Skill to rolls.  If you check the actors sheets it may have an Initiative of 3, 8 or 10 but when you add the tokens to the encounter and click "Roll NPCs" or click the dice on each it will roll a D20 and assign the number on the dice as the initiative.  If you open each sheet and click the dice next to Initiative skill it works properly.

**Comment by kypvalanx** [comment]
I took a look at this as part of the current work i'm doing with skills and i cannot replicate it at this time.  the actual roll should be appearing in the chat log as well.  it's possible that while fixing other things i fixed the issue this was having, but i don't think that's the case.

**Comment by kypvalanx** [comment]
got it, will be on next release
