### ISSUE TITLE
All Vehicles are busted and don't work properly

### ISSUE THREAD

**Issue by DiamonDKZ** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#485]
[fvtt-Actor-at-te-J7sApohhQE8sQrU6.json](https://github.com/user-attachments/files/16180005/fvtt-Actor-at-te-J7sApohhQE8sQrU6.json)

**Comment by kypvalanx** [comment]
this isn't a particularly helpful issue.  can you describe the specific things that do not work?

**Comment by DiamonDKZ** [comment]
Vehicle armor don't work (reflex defense especially), skill macross don't work. Adding systems don't show up, attack macross even for default weapon don't show up

**Comment by kypvalanx** [comment]
- [ ] Vehicle armor don't work (reflex defense especially)
- [ ] skill macros don't work
- [ ] Added vehicle systems don't show up
- [ ] attack macros even for default weapon don't show up (i think this means the attack card on the summary tab)
