### ISSUE TITLE
Applying ability point upgrades at lvl 4 clears out all ability scores

### ISSUE THREAD

**Issue by TalonKetupa** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#50]
Made Actor and populated data. Increased level to 4. Selected attribute placement. Finalized by clicking YES.
Instantly all previously set ability scores disappear. Attempts to set ability scores does nothing henceforth.
Console shows this error afterwards:

Uncaught (in promise) TypeError: Cannot read property 'value' of null
    at resolveValueArray (util.js:28)
    at generateAttributes (attribute-handler.js:53)
    at SWSEActor._prepareCharacterData (actor.js:74)
    at async SWSEActor.prepareData (actor.js:34)

**Comment by kypvalanx** [comment]
The real problem was a np. This should work now
