### ISSUE TITLE
[Bug][12.3.1] Cannot resolve targeted attacks

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#505]
**Steps to reproduce:** put two tokens on the scene, target one token, attack with another - nothing. 
**Error:** 
![image](https://github.com/user-attachments/assets/b1ae38e6-4834-46dd-990a-a52cff55034e)

**Comment by kypvalanx** [comment]
this has been fixed in 12.3.7
