### ISSUE TITLE
Talent: Cargo Hauler should double the carrying capacity

### ISSUE THREAD

**Issue by Giodibi** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#511]
The Cargo Hauler talenf from 5th-Degree Droind Talen Tree should double the carrying capacity, but it's not.

**Comment by kypvalanx** [comment]
![image](https://github.com/user-attachments/assets/bcc6dfc5-2d7b-451d-aa2a-073826874427)
 this will show up in 12.3.5
