### ISSUE TITLE
Level up bonuses not working

### ISSUE THREAD

**Issue by McCookies** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#517]
The dialog box shows up to pick the every 4th level stat bonuses, but after you select them, the sheet doesn't reflect the improved stats.  The stat changes are shown on the Changes tab.  I first noticed this a few weeks ago.  It was working a couple months ago when my PCs hit level 8.

<img width="584" alt="Screenshot 2024-12-16 at 04 24 27" src="https://github.com/user-attachments/assets/f8f27afb-9a9a-4061-aeb3-68824eee5932" />
<img width="514" alt="Screenshot 2024-12-16 at 04 26 27" src="https://github.com/user-attachments/assets/cde94a0e-80a6-4da7-a478-901f5d53cbd9" />
<img width="432" alt="Screenshot 2024-12-16 at 04 26 50" src="https://github.com/user-attachments/assets/482fbb55-efd4-44b9-b052-de6efd0dfb33" />
<img width="964" alt="Screenshot 2024-12-16 at 04 29 25" src="https://github.com/user-attachments/assets/212b03ca-5160-4095-9250-5d7ec1f1d232" />

**Comment by kypvalanx** [comment]
this is working in latest release

**Comment by McCookies** [comment]
Thanks.  It isn't working (retroactively) for an existing character though.  I'll rebuild my characters after my game session tomorrow.  My level-up bonuses are in the temp column for now.
