### ISSUE TITLE
Adding Class Starting Feats will get the warning that I select too many feats than allowed.

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#57]
It should not show warning and if possible, automativally add the starting feats

![image](https://user-images.githubusercontent.com/22677493/150141505-fa2e43ad-08f6-4733-9f68-6eaf47a1b25f.png)

**Comment by kypvalanx** [comment]
looks like it had an issue adding the shake it off feat.  from the garbage can icon i can tell you added it yourself, so the warning is correct.  i'll see what i can find.  thank you for such specific issue reporting.

**Comment by sanpats** [comment]
Are starting feats supposed to be added automatically, or manually?
