### ISSUE TITLE
Wookiee when equip with weapon the sheet will bug out

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#59]
The latest version 0.4.5 make Wookiee when equip with weapon (I tested with bowcaster and spear), the sheet will bug out.
![image](https://user-images.githubusercontent.com/22677493/150341559-266c9f79-35e7-4845-b0ea-d5c810b08d8e.png)

**Comment by kypvalanx** [comment]
can you hit F12 to open the console and look at the log for an error?

**Comment by sanpats** [comment]
![image](https://user-images.githubusercontent.com/22677493/150371099-07be754e-2a9a-4200-815a-9b930b94e247.png)
