### ISSUE TITLE
Feats dragged to character sheet do not display until character sheet is closed and reopened

### ISSUE THREAD

**Issue by jasony1974** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#6]
Feats dragged to character sheet do not display until character sheet is closed and reopened.  It appears that the feat.bonusFeatCategories property is undefined.

The following error appears in console.log:

actor.mjs:1007 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at SWSEActor._reduceProvidedItemsByExistingItems (actor.mjs:1007)
    at SWSEActor._prepareCharacterData (actor.mjs:57)
    at async SWSEActor.prepareData (actor.mjs:27)

**Comment by kypvalanx** [comment]
i think this is now resolved in master

**Comment by jasony1974** [comment]
Nope.  I've updated, and there's still something not right.

Here are the steps I followed:

1. create new actor - character
2. set ability scores
3. add species
4. add general feat

Note in the attached screenshots that, after adding the species, the traits for the species are displayed, but hte name of the species is not.  After adding the general feat - I used "Improved Defenses" - the Defense, Offense, Attacks, and  Abilities sections of the Summary tab are blanked out.  If I close & reopen the character sheet, the Feat is displayed, but the sections on the summary tab are still blank.  If I remove the feat, by clicking the trash can icon, the sections on the summary tab repopulate. See numbered screenshots.

Additionally, the issue of the species specify traits remaining after the species is deleted is still there.  See "species delete" screenshot.
![character creation step 1](https://user-images.githubusercontent.com/79643334/116573127-8acd9d80-a8da-11eb-8a12-65171be71fa1.png)
![character creation step 2 - assign ability scores](https://user-images.githubusercontent.com/79643334/116573141-8c976100-a8da-11eb-8226-0b0419ca65fa.png)
![character creation step 3 - add species](https://user-images.githubusercontent.com/79643334/116573174-91f4ab80-a8da-11eb-8a89-e842096cd836.png)
![character creation step 4 - add general feat](https://user-images.githubusercontent.com/79643334/116573185-93be6f00-a8da-11eb-8219-6f34a9761a3c.png)
![species delete](https://user-images.githubusercontent.com/79643334/116573197-95883280-a8da-11eb-8bca-6e5aaf242e83.png)

**Comment by jasony1974** [comment]
just for reference purposes, I'm using:

Edition	Windows 10 Pro
Version	20H2
Installed on	‎3/‎12/‎2021
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

Foundry 0.7.9 - local install

Google Chrome is up to date
Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by kypvalanx** [comment]
looks like you might have found a duros specific issue.  there's something wrong with the generated data

**Comment by kypvalanx** [comment]
I've released a fix #0.2.3
