### ISSUE TITLE
Nonheroic level shouldn't be added to defenses

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#60]
I tried to create a stormtrooper npc template. The class is nonheroic, but the nonheroic level got added to defenses.
![image](https://user-images.githubusercontent.com/22677493/150342101-c21e63fe-21d8-4062-9192-09c875e33f8c.png)

**Comment by kypvalanx** [comment]
the method for resolving the number of heroic levels was checking if the class was named Beast or NonHeroic.  the class is called Nonheroic.  i'll get it working that way for now but this needs a little more work.

**Comment by sanpats** [comment]
That's okay, but Nonheroic was how it spell in the included compendium.

**Comment by kypvalanx** [comment]
yeah, it's a mistake on my part
