### ISSUE TITLE
Human Scoundrel get 1 too many feat at level 1

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#63]
Human Scoundrel should get 2 general feats at level 1, right? Not 3. And they should have +1 trained skill. A human scoundrel with +2 int mod should get 4+2 (int mod) +1 (from being human), but I got only 6

![image](https://user-images.githubusercontent.com/22677493/150481782-654dbd54-9a82-4698-83f3-a459b392d566.png)

**Comment by sanpats** [comment]
It seem to be a bug on all human, not just scoundrel.

**Comment by kypvalanx** [comment]
you're correct.  looks like bonus feat is double adding and bonus trained skill is not providing a trained skill
