### ISSUE TITLE
HP bar on tokens show incorrectly

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#66]
HP 6/6 showed like it is 6/10.
![image](https://user-images.githubusercontent.com/22677493/150489410-4e459b79-bdd5-45f6-be3a-9ebee1da6dfe.png)

**Comment by sanpats** [comment]
Change map seems to solve it. Only bug when first placed on maps.

**Comment by sanpats** [comment]
When open the first map on newly opened Foundry, it will bug again. Change map will fix it, but F5 won't.

**Comment by kypvalanx** [comment]
this one will take me a bit.  it doesn't even consistently correct itself when i update the token.

**Comment by kypvalanx** [comment]
I think that the changes i did for #81 should also fix this

**Comment by sanpats** [comment]
I think it's fixed.
