### ISSUE TITLE
Error adding Weapon Focus Feat

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#67]
Sometime adding weapon focus feat show this error, and the feat won't show up so I can't delete it.
![image](https://user-images.githubusercontent.com/22677493/150499927-f44a4dda-03d8-448f-a2e0-20e00c5c1f20.png)

**Comment by kypvalanx** [comment]
this same issue was happening with #64 after fixing the initial problem.  checking now
