### ISSUE TITLE
Small Size Adjustments are not working

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#68]
1. Ref Def doen't get +1
2. Stealth bonus cause earror (see below)
![image](https://user-images.githubusercontent.com/22677493/150591397-fd44a25a-4592-4380-972c-5b2641200c1e.png)

**Comment by kypvalanx** [comment]
which species did you use?  I cleaned up some code addressing other issues and it seems to work for ewoks

**Comment by kypvalanx** [comment]
oh, nevermind, just got it to break
