### ISSUE TITLE
Bonus Trained Skill for Human still doesn't work.

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#71]
The latest update fix feat bonus, but the trained skill bonus still doesn't work (doesn't provide +1 trained skill).

**Comment by kypvalanx** [comment]
after fixing #70 locally i tried this one and it seems to work.  you should see a yellow notification saying:
![image](https://user-images.githubusercontent.com/7539264/150642268-325d03ce-de6d-4211-986d-296c95b3e2c5.png)
 and that should increase.  
 
 if that works for you, is there a different way you were expecting to be notified?  i can add more feedback if it's unclear.

**Comment by sanpats** [comment]
This is newly created Human Scoundrel lv 1. With INT mod 0, the scoundrel should have 4 (from being scoundrel) + 1 (human bonus) = 5, not 4.

**Comment by sanpats** [comment]
![image](https://user-images.githubusercontent.com/22677493/150643628-2278f35e-becf-48e1-8882-b98e05e02222.png)

**Comment by kypvalanx** [comment]
found the problem

**Comment by kypvalanx** [comment]
0.4.10 should fix it.  i created the attribute and forgot to assign it to the trait

**Comment by sanpats** [comment]
fixed

**Comment by kypvalanx** [comment]
thank you, your feedback has been invaluable!
