### ISSUE TITLE
Nonheroic NPCs do not gain 1d4 HP at any level.

### ISSUE THREAD

**Issue by BangoeRette** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#75]
Nonheroic NPCs do not gain +1d4 HP at first level, or any level. They only gain CON mod.
![image](https://user-images.githubusercontent.com/93169227/150649992-5cfb4da5-bcb8-4b8c-bae6-9abf6613ce9f.png)
![image](https://user-images.githubusercontent.com/93169227/150649957-c640c131-9e43-4020-aaa5-7e076a1fbe2b.png)

**Comment by sanpats** [comment]
I experienced the same thing. I have to manually add an attribute "firstLevelHitpoints" to the first level. The subsequent levels have redundant "isFirstLevel" attributes that needed to be deleted manually.

**Comment by kypvalanx** [comment]
added, they should be there next release, which will probably be tomorrow
