### ISSUE TITLE
Not having Armor Proficiency Feat should still get armor bonus to Ref Def

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#79]
![image](https://user-images.githubusercontent.com/22677493/150689430-940745d6-a2f7-4a3e-91e6-92e4e696efd7.png)

"Additionally, you do not gain the armor's **'equipment' bonuses**. For example, a character not proficient with light armor who dons a suit of stormtrooper armor takes a -2 penalty on attack rolls and certain skill checks (see above) . In addition, he does not gain the armor's equipment bonus on Perception checks and cannot apply the armor's equipment bonus to his Fortitude Defense."

Not having Armor Proficiency make you can't gain 'equipment' bonus (such as the one to Fort Def), but still grant you 'armor' bonus in place of level in Ref Def. Otherwise there is no point in wearing armor unproficiently.

![image](https://user-images.githubusercontent.com/22677493/150689560-03be8233-7af0-4aca-b67c-50f628c26e92.png)

**Comment by sanpats** [comment]
![image](https://user-images.githubusercontent.com/22677493/150689637-746b3c57-7f76-4b78-bf53-6ace4576c4ab.png)

**Comment by sanpats** [comment]
![image](https://user-images.githubusercontent.com/22677493/150689677-8a1e85e8-b20d-45a5-bea6-1560d999e15d.png)

**Comment by kypvalanx** [comment]
Looks like I misread that.

**Comment by kypvalanx** [comment]
if i'm understanding correctly, the only stats that i should honor for armor that the user is not proficient with is the reflex bonus and the max dex bonus.  so if i hid all attributes except those two when the character is not proficient that would be ideal.

**Comment by sanpats** [comment]
I think you are correct.
