### ISSUE TITLE
All characters should proficient at unarmed and natural weapon

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#94]
When not having Weapon Profociency (Simple Weapon) Feat, the unarmed attack got -5 penalty as if not proficient.

According to the latest official errata:
“Unarmed attacks and natural weapons are considered light simple weapons in which all characters are proficient.”

All characters should proficient at unarmed and natural weapon.

**Comment by kypvalanx** [comment]
do you have a link to that errata so i can check other things?

**Comment by kypvalanx** [comment]
i'll fix unarmed attacks today.  beasts need a little TLC. when i get to that i'll fix natural attacks.

**Comment by sanpats** [comment]
https://rpg.fandom.com/wiki/Star_Wars_Saga_Edition_Official_Errata#:~:text=proficient%20with%20them.%20%E2%80%9C-,p.%20120%20%E2%80%93%20Simple%20Weapons,-Add%20the%20following

**Comment by sanpats** [comment]
http://swse.xphilesrealm.com/WizardsOfTheCoast/WotcWebPages/Star%20Wars%20Roleplaying%20Game%20Saga%20Edition%20Errata%20and%20Official%20Clarifications.htm

**Comment by sanpats** [comment]
Official Errata & Clarifications
