### ISSUE TITLE
Build out Creature Generator

### ISSUE THREAD

**Issue by kypvalanx** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#95]
https://swse.fandom.com/wiki/Creating_New_Beasts#Creature_Generator

- [x]  Roll or select [Ability Scores](https://swse.fandom.com/wiki/Ability_Scores). Select an [Intelligence](https://swse.fandom.com/wiki/Intelligence) score of 1 or 2. An advanced Beast species with [Intelligence](https://swse.fandom.com/wiki/Intelligence) of 3 or above can [Multiclass](https://swse.fandom.com/wiki/Multiclass) into [Heroic Classes](https://swse.fandom.com/wiki/Heroic_Classes), but must begin with its first level in the [Beast](https://swse.fandom.com/wiki/Beast) class.
- [x]  Increase one [Ability Score](https://swse.fandom.com/wiki/Ability_Score) by 1 point at every fourth level, if the Beast is above 1st level.
- [x]  Select the Beast's Size and apply the appropriate modifiers (see Base Modifiers).
- [x]  Add Hit Points (1d8 + [Constitution](https://swse.fandom.com/wiki/Constitution) modifier per level).
- [x]  Beasts do not have [Force Points](https://swse.fandom.com/wiki/Force_Points). However, if a Beast has the [Force Sensitivity](https://swse.fandom.com/wiki/Force_Sensitivity) Feat, assign it a number of [Force Points](https://swse.fandom.com/wiki/Force_Points) equal to one-half its Beast Level (minimum 1). #234 
- [x]  Select a speed for the creature (see Base Statistics). If the creature has other movement methods (such as Swim or Fly), select those speeds as well.
- [x]  Determine the Beast's [Defenses](https://swse.fandom.com/wiki/Defenses) and [Damage Threshold](https://swse.fandom.com/wiki/Damage_Threshold) (see Base Defenses). Apply Natural Armor, if any, adding a Natural Armor bonus to [Reflex Defense](https://swse.fandom.com/wiki/Reflex_Defense) equal to or lower than the creature's Beast Level. Some   Natural Armor grants additional effects as a special quality (and counts as one of the Beast's Special Qualities).
- [x]  Add [Feats](https://swse.fandom.com/wiki/Feats) at the rate for normal characters (at 1st, 3rd, 6th, 9th, 12th, 15th, and 18th Level). The [Beast](https://swse.fandom.com/wiki/Beast) Class does not grant additional starting [Feats](https://swse.fandom.com/wiki/Feats).
- [x]  Select a number of [Trained Skills](https://swse.fandom.com/wiki/Trained_Skills) equal to 1 + [Intelligence](https://swse.fandom.com/wiki/Intelligence) modifier (minimum 1). Apply the size modifier to [Stealth](https://swse.fandom.com/wiki/Stealth), as well as modifiers to other [Skills](https://swse.fandom.com/wiki/Skills), such as Size or [Feat](https://swse.fandom.com/wiki/Feat) modifiers.
- [x]  Select one to three Natural Weapons, and determine the Beast's melee attack and damage with its Natural Weapons (see Base Attacks).
- [x]  Determine the Beast's [Grapple](https://swse.fandom.com/wiki/Grapple) modifier (see Base Attacks): [Base Attack Bonus](https://swse.fandom.com/wiki/Base_Attack_Bonus) + [Strength](https://swse.fandom.com/wiki/Strength) or [Dexterity](https://swse.fandom.com/wiki/Dexterity) modifier (whichever is better) + Size modifier.
- [x]  Select any Special Senses, such as Low-Light Vision or Darkvision.
- [x]  Select a Species Type, if desired.
- [x]  Select from zero to three Special Qualities. You can create them yourself, or select from those discussed below.

**Comment by sanpats** [comment]
Any plan on Vehicle Sheet?
