### ISSUE TITLE
Natural armor should be added to Misc, not Level/Armor

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#98]
Natural armor should be added to Misc column, not Level/Armor column of Ref Def.
![image](https://user-images.githubusercontent.com/22677493/151032378-f5a1a5ea-31f1-4d82-9b94-b5bab1ca2a29.png)
From the core rulebook:
![image](https://user-images.githubusercontent.com/22677493/151032566-fc0bd167-5d57-4b3f-a466-53d118429c5d.png)

As you can see, natural armor bonus and size modifier are belong to misc bonus of Reflex defense.

**Comment by kypvalanx** [comment]
it looks like it already is.  in the Chevin case, it gets -1 from size and +1 from natural armor.  both are being applied in the misc category, but i'll take this as an opportunity to add a breakdown tooltip.

**Comment by sanpats** [comment]
You are correct, my apologies.
